### ISSUE TITLE
Klangfalter's GUI only opens twice

### ISSUE THREAD

**Issue by suedwestlicht** [falkTX/Carla#288] opened 2015-08-02 18:28 UTC
When I load Klangfalter it works fine but its GUI only opens twice correctly. The third open only shows the window borders and the contents of the underlying Carla window.

Carla doesn't output any lines on the console when loading Klangfalter and opening the GUI.

The same happens with other DISTRHO plugins like The Pilgrim and The Function.

The issue doesn't occur in Qtractor and Ardour.

![klangfalter_in_carla](https://cloud.githubusercontent.com/assets/5550538/9027429/093c8c4a-3955-11e5-9b38-8622e7289795.png)

**Comment by suedwestlicht** [comment] 2015-08-02 18:48
I forgot: It's the LV2 versions. I didn't compile the VST plugins of DISTRHO.

**Comment by distrozapper** [comment] 2015-08-02 20:58
Hi & welcome suedwestlicht,
Just to add info:
I can't reproduce this issue on ubuntu 14.04 64bit/KDE4/kxstudio repos/carla-git, all update, no selfcompiled things.
Yet, when adding klangfalter LV2 to the carla rack, carla reports this in terminal:

Carla assertion failure: "fLatencyIndex == static_cast<int32_t>(j)" in file CarlaPluginLV2.cpp, line 2196

Klangfalter's GUI can be opened/closed multiple times without issue though.
I also tried dexed lv2 without issue.
What distro/DE are you on please?

**Comment by suedwestlicht** [comment] 2015-08-02 21:05
I use Xubuntu 12.04 LTS 64 Bit. Carla ist the latest version from Git. DISTRHO is
DISTRHO-Ports.217 dated 2014-11-06. Maybe it's too old?

**Comment by distrozapper** [comment] 2015-08-02 21:28
Hm, IIRC falktx dropped support for 12.04 LTS and debian wheezy already.
So maybe yes, the DISTRHO ports might be outdated.
I am sure falktx will give you better advice.
Just in case you don't know: The kxstudio site has moved now to http://kxstudio.linuxaudio.org

**Comment by falkTX** [comment] 2015-08-03 01:10
ah, you're a 12.04 user.
yes, that no longer has updates from kxstudio.
so this might be already fixed.

**Comment by suedwestlicht** [comment] 2015-08-03 18:20
With a recent DISTRHO and Carla from Git everything works fine, even on Xubuntu 12.04.

Thank you and sorry for any inconvenience.

**Comment by falkTX** [comment] 2016-01-09 18:57
I've made some changes to the juce-lv2 wrapper that should helps this a bit more as well.
I consider this fixed now. If it still happens let me know.
Just make sure to get the latest distrho-ports and carla from git first.

**Closed by falkTX** 2016-01-09 18:57 UTC
