### ISSUE TITLE
Plugin instruments disconnected when loading a preset bank

### ISSUE THREAD

**Issue by amsynthdotcom** [falkTX/Carla#454] opened 2017-01-10 20:32 UTC
(Debian, "Jessie," 32-bit)
Tested on both WhySynth and Xsynth, when loading a preset bank the midi and audio connections in the patchbay have to be remade.

brian

**Comment by falkTX** [comment] 2017-04-08 06:28
Is this carla 1.x or git version?

**Comment by falkTX** [comment] 2017-07-31 09:37
hello?

**Comment by falkTX** [comment] 2017-07-31 09:39
Doesn't seem to be an issue anymore with the latest version.
Please confirm, otherwise I'll close the issue in a few days.

**Comment by falkTX** [comment] 2017-09-14 21:17
Can't reproduce, closing issue.

**Closed by falkTX** 2017-09-14 21:17 UTC
Labels: bug, needs more info
