### ISSUE TITLE
sfz loaded in ardour via carla-rack stops working after reload

### ISSUE THREAD

**Issue by rhetr** [falkTX/Carla#250] opened 2015-05-07 08:01 UTC
I have a number of ardour tracks with their own carla-racks containing various sfzs. When I reload the session I don't get any sound out of them and I have to clone + remove the sfzs in the carla-rack to get them to work again.

**Comment by falkTX** [comment] 2015-05-08 08:01
I cannot reproduce this.
What ardour version are you using? (it's working fine here with the official ardour4 binary)

**Comment by rhetr** [comment] 2015-05-08 11:30
Using ardour4 with the kxstudio carla-git. My setup is that I have 4 tracks, violin1 violin2 viola and cello in that order. I ran ardour from the terminal and this is what it outputs:

    Scheduling '/media/Data/audio/sounds/sfz/Sonatina Symphonic Orchestra/Strings - 1st Violins Sustain.sfz' (Index=0) to be loaded in background (if not loaded yet).
    Loading sfz file '/media/Data/audio/sounds/sfz/Sonatina Symphonic Orchestra/Strings - 1st Violins Sustain.sfz'...OK
    Loading sfz instrument ('/media/Data/audio/sounds/sfz/Sonatina Symphonic Orchestra/Strings - 1st Violins Sustain.sfz',0)...OK
    Caching initial samples...OK
    Stopping disk thread...OK
    Starting disk thread...OK
    EQ support: no
    Starting disk thread...OK
    EQ support: no
    Stopping disk thread...OK
    Starting disk thread...OK
    EQ support: no
    Scheduling '/media/Data/audio/sounds/sfz/Sonatina Symphonic Orchestra/Strings - 2nd Violins Sustain.sfz' (Index=0) to be loaded in background (if not loaded yet).
    Loading sfz file '/media/Data/audio/sounds/sfz/Sonatina Symphonic Orchestra/Strings - 2nd Violins Sustain.sfz'...OK
    Loading sfz instrument ('/media/Data/audio/sounds/sfz/Sonatina Symphonic Orchestra/Strings - 2nd Violins Sustain.sfz',0)...OK
    Caching initial samples...OK
    Stopping disk thread...OK
    Starting disk thread...OK
    EQ support: no
    Stopping disk thread...OK
    Starting disk thread...OK
    EQ support: no
    Starting disk thread...OK
    EQ support: no
    Stopping disk thread...OK
    Starting disk thread...OK
    EQ support: no
    Scheduling '/media/Data/audio/sounds/sfz/Sonatina Symphonic Orchestra/Strings - Violas Sustain.sfz' (Index=0) to be loaded in background (if not loaded yet).
    Loading sfz file '/media/Data/audio/sounds/sfz/Sonatina Symphonic Orchestra/Strings - Violas Sustain.sfz'...OK
    Loading sfz instrument ('/media/Data/audio/sounds/sfz/Sonatina Symphonic Orchestra/Strings - Violas Sustain.sfz',0)...OK
    Caching initial samples...OK
    Stopping disk thread...OK
    Starting disk thread...OK
    EQ support: no
    Stopping disk thread...OK
    Starting disk thread...OK
    EQ support: no
    Stopping disk thread...OK
    Starting disk thread...OK
    EQ support: no
    Starting disk thread...OK
    EQ support: no
    Stopping disk thread...OK
    Starting disk thread...OK
    EQ support: no
    Scheduling '/media/Data/audio/sounds/sfz/Sonatina Symphonic Orchestra/Strings - Celli Sustain.sfz' (Index=0) to be loaded in background (if not loaded yet).
    Loading sfz file '/media/Data/audio/sounds/sfz/Sonatina Symphonic Orchestra/Strings - Celli Sustain.sfz'...OK
    Loading sfz instrument ('/media/Data/audio/sounds/sfz/Sonatina Symphonic Orchestra/Strings - Celli Sustain.sfz',0)...OK
    Caching initial samples...OK
    drop flushed event on the floor, time drop flushed event on the floor, time 0 too early for 0 too early for 00 + 240 90  + f0 902c  4d 3c
    67

the result is that only the Cello gets loaded, the first three tracks remain unloaded and I have to clone+remove them (either in ardour or in the carla-rack) for them to load properly.

**Comment by falkTX** [comment] 2015-10-11 21:42
this needs testing against the latest ardour git version.
quite a few things have changed in how ardour handles plugins and their state (via lilv), so this might or not still be an issue.
when you have time, please retest against the latest ardour (either git version or wait for 4.3)

**Comment by Thekian** [comment] 2015-11-11 17:49
I have a very similar issue occurring in LMMS. Only the last carla track using a sfz in a project has any sound. I tried installing KXStudio in a virtual machine yesterday, and it has exactly the same issue (all packages updated).

I used to be able to workaround this by having a carla rack inside a carla patchbay, but this no longer works. Interestingly enough using different Carla-Rack plugins (labeled carlarack and http://kxstudio.sf.net/carla/plugins/carlarack in the plugin list) inside the patchbay allows me to have two tracks working properly.

Below is a log (anonymized) from LMMS where I simply play back the file. Only the "Violin Solo" and the "Cello Solo" is playing.

```
VST sync support disabled in your configuration
Starting disk thread...OK
EQ support: no
Stopping disk thread...OK
Starting disk thread...OK
EQ support: no
Scheduling '~/lmms/sf2/Keys - Grand Piano.sfz' (Index=0) to be loaded in background (if not loaded yet).
Loading sfz file '~/lmms/sf2/Keys - Grand Piano.sfz'...OK
Loading sfz instrument ('~/lmms/sf2/Keys - Grand Piano.sfz',0)...OK
Caching initial samples...OK
Stopping disk thread...OK
Starting disk thread...OK
EQ support: no
Starting disk thread...OK
EQ support: no
Stopping disk thread...OK
Starting disk thread...OK
EQ support: no
Scheduling '~/lmms/sf2/Keys - Grand Piano.sfz' (Index=0) to be loaded in background (if not loaded yet).
Stopping disk thread...OK
Starting disk thread...OK
EQ support: no
Stopping disk thread...OK
Starting disk thread...OK
EQ support: no
Starting disk thread...OK
EQ support: no
Stopping disk thread...OK
Starting disk thread...OK
EQ support: no
Scheduling '~/lmms/sf2/Strings - Basses Sustain.sfz' (Index=0) to be loaded in background (if not loaded yet).
Loading sfz file '~/lmms/sf2/Strings - Basses Sustain.sfz'...OK
Loading sfz instrument ('~/lmms/sf2/Strings - Basses Sustain.sfz',0)...OK
Caching initial samples...OK
Will use LV2 X11 UI
lv2ui_extension_data("http://lv2plug.in/ns/extensions/ui#idleInterface")
lv2ui_extension_data("http://lv2plug.in/ns/extensions/ui#showInterface")
lv2ui_extension_data("http://lv2plug.in/ns/extensions/ui#resize")
lv2ui_extension_data("http://kxstudio.sf.net/ns/lv2ext/programs#UIInterface")
Starting disk thread...OK
EQ support: no
Stopping disk thread...OK
Starting disk thread...OK
EQ support: no
Scheduling '~/lmms/sf2/Strings - Cello Solo.sfz' (Index=0) to be loaded in background (if not loaded yet).
Loading sfz file '~/lmms/sf2/Strings - Cello Solo.sfz'...OK
Loading sfz instrument ('~/lmms/sf2/Strings - Cello Solo.sfz',0)...OK
Caching initial samples...OK
Stopping disk thread...OK
Starting disk thread...OK
EQ support: no
Stopping disk thread...OK
Starting disk thread...OK
EQ support: no
Stopping disk thread...OK
Starting disk thread...OK
EQ support: no
Starting disk thread...OK
EQ support: no
Stopping disk thread...OK
Starting disk thread...OK
EQ support: no
Scheduling '~/lmms/sf2/Strings - Violin Solo.sfz' (Index=0) to be loaded in background (if not loaded yet).
Loading sfz file '~/lmms/sf2/Strings - Violin Solo.sfz'...OK
Loading sfz instrument ('~/lmms/sf2/Strings - Violin Solo.sfz',0)...OK
Caching initial samples...OK
```

**Comment by falkTX** [comment] 2015-12-22 12:43
a few people have reported this, so it must be a really important bug.
I'll see if I can get it fixed before the next release.

**Comment by falkTX** [comment] 2015-12-29 12:57
I investigated this yesterday, extensively, but couldn't find a definitive answer.
But I was able to get some more info.
The issue happens only when loading a carla-rack/patchbay plugin project.

After the carla plugin is loaded you can use the export action, then remove all, then re-import the exported project and it will work fine..
I don't really know what's going on.

I added a workaround for this in the mean time.
GIG and SFZ files loaded inside a carla-plugin instance will run in bridge mode.
This will increase cpu and use a lot more ram (no more shared sample data), but it will work for now until we find a definitive answer.

**Comment by falkTX** [comment] 2016-01-01 04:29
there's some smarter code to workaround this issue in carla now.
the bridge mode is only used when loading a project that contains gig/sfz inside carla-rack/patchbay plugin and it's not the first instance used.

so if you for example only use 1 sfz per carla-rack, there will be no performance penalty whatsoever.

I'm changing the milestone of this bug to 2.0-final since we have a working workaround.
Good enough for the next beta :)

**Comment by falkTX** [comment] 2018-07-21 19:39
I just added some more aggressive things to try to make linuxsampler behave better...
Might fix our issue, might change nothing at all... testing welcome.
Will push the new changes to the kx repos now, beta7 release will include these changes.

**Comment by aki-k** [comment] 2018-07-23 12:15
Your update seems to have fixed my problem with Ardour and two Carla-racks. Now they remember the sfzs that I've added. Thank you.

**Comment by falkTX** [comment] 2018-07-23 14:09
alright, this is nice. I was not sure if the fix would work or not.
It is quite the hack, but something to handle better sometime later.
Better to have it working and use a bit too much resources, than not working at all.

Closing this issue then.

**Comment by codecollider** [comment] 2018-07-23 16:36
I still have the problem that Carla 1.9.9 (2.0. beta 7) looses SFZ instruments when reloading Reaper. This is not always the case, but sometimes (especially after reboot).

**Comment by aki-k** [comment] 2018-08-06 16:32
On another session in Ardour, I also now have a Carla-rack that on reload is empty :( The session also has Synth1 VSTi (Windows) and two ZynAddSubFX LV2s.

**Comment by aki-k** [comment] 2018-08-07 13:07
Maybe I was unclear. The Carla-rack that opened as empty had a SFZ in it.

**Comment by falkTX** [comment] 2018-08-07 13:31
ah okay, sorry I misunderstood.
I thought you meant that it was happening with other plugins besides sfz files.

can someone do me a big a favor and create a small ardour project where this issue is triggered?
using an available SFZ library (for free) would be preferable, so I can try to reproduce the issue.
will lead to get this fixed a lot faster.
thank you

**Comment by aki-k** [comment] 2018-08-08 18:02
I can trigger this issue so that it can be repeated. It seems to happen only after the first reload of the newly created session in Ardour. Do you prefer if I list the steps in text or do you want to have a copy of the session?

**Comment by codecollider** [comment] 2018-08-08 19:47
I can make a REAPER project if it helps where the problem can be reproduced. 
REAPER (8 mb in total) can be downloaded from the official website, extracted and is then ready to run. No installation needed. In addition you need the VSCO sfz library. (https://github.com/sgossner/VSCO-2-CE)

**Comment by aki-k** [comment] 2018-08-08 19:59
Here's the saved Ardour session which on load gives no sound from the Taiko Drum midi track.

https://transfer.sh/16jLm4/carla-rack-empty-3.tar.gz

I've used these two SFZs that are stored in $HOME/.sounds/sfz:

The Shrine Piano v1.3:
https://musical-artifacts.com/artifacts/460

Taiko Drum:
https://www.fiedler-audio.de/creative-commons-library/

**Comment by falkTX** [comment] 2018-08-09 13:42
@aki-k Thanks for uploading the files!
Sadly, I cannot reproduce the issue here. the plugins get loaded correctly (after I adjusted the filename).

![image](https://user-images.githubusercontent.com/1334853/43902509-9380c696-9bea-11e8-9c12-0e0b7c3cca91.png)

These are my entire logs from ardour, running in a terminal: (not ardour log window!)
```
$ ardour carla-rack-empty-3.ardour
bind txt domain [gtk2_ardour5] to /opt/ardour/share/locale
Ardour5.12.0 (built using 5.12 and GCC version 4.4.7)
ardour: [INFO]: Your system is configured to limit Ardour to only 65536 open files
ardour: [INFO]: Loading system configuration file /opt/ardour/etc/system_config
ardour: [INFO]: Loading user configuration file /Shared/.falktx-links/config/ardour5/config
ardour: [INFO]: CPU vendor: GenuineIntel
ardour: [INFO]: AVX-capable processor
ardour: [INFO]: CPU brand: Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
ardour: [INFO]: Using SSE optimized routines
Cannot xinstall SIGPIPE error handler
ardour: [INFO]: Loading default ui configuration file /opt/ardour/etc/default_ui_config
ardour: [INFO]: Loading user ui configuration file /Shared/.falktx-links/config/ardour5/ui_config

(ardour-5.12.0:25612): Gtk-WARNING **: Unable to locate theme engine in module_path: "qtcurve",
Color shuttle bg not found
ardour: [INFO]: Loading color file /opt/ardour/share/themes/dark-ardour.colors

(ardour-5.12.0:25612): Gtk-WARNING **: Unable to locate theme engine in module_path: "qtcurve",
ardour: [INFO]: Loading ui configuration file /opt/ardour/etc/clearlooks.rc
ardour: [INFO]: Loading ui configuration file /opt/ardour/etc/clearlooks.rc
Found nothing along /home/falktx/.config/ardour5/templates:/opt/ardour/share/templates
convolution: samplerate mismatch preset:48000 host:44100
convolution: samplerate mismatch preset:48000 host:44100
convolution: samplerate mismatch preset:48000 host:44100
RemoteVSTClient: all cache files are up-to-date, not running scanner
convolution: samplerate mismatch preset:48000 host:44100
convolution: samplerate mismatch preset:48000 host:44100
convolution: samplerate mismatch preset:48000 host:44100
convolution: samplerate mismatch preset:48000 host:44100
convolution: samplerate mismatch preset:48000 host:44100
convolution: samplerate mismatch preset:48000 host:44100
RemoteVSTClient: all cache files are up-to-date, not running scanner
convolution: samplerate mismatch preset:48000 host:44100
convolution: samplerate mismatch preset:48000 host:44100
convolution: samplerate mismatch preset:48000 host:44100
Scanning folders for bundled LV2s: /opt/ardour/lib/LV2
error: /usr/lib/lv2/Freakclip.lv2/Freakclip.ttl:36:4: missing ';' or '.'
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/Freakclip.lv2/Freakclip.ttl'
error: /usr/lib/lv2/Granulator.lv2/Granulator.ttl:24:7: missing ';' or '.'
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/Granulator.lv2/Granulator.ttl'
Set cursor set to default
Plugin binary '/home/akik/.sounds/sfz/The Shrine Piano v1.3.sfz' doesn't exist on this filesystem, let's look for it...
Found it! :)
starting plugin bridge, command is:
/usr/lib/lv2/carla.lv2/carla-bridge-native "SFZ" "/home/falktx/Personal/Muzyks/Kits/SFZ/Shrine Piano v1.3/SFZ/The Shrine Piano v1.3.sfz" """" 0
CarlaThread with realtime priority successful
Starting disk thread...OK
EQ support: no
The opcode 'label_cc15' is unsupported by libsfz!
The opcode 'label_cc16' is unsupported by libsfz!
The opcode 'label_cc64' is unsupported by libsfz!
The opcode 'sustain_sw' is unsupported by libsfz!
Stopping disk thread...OK
Starting disk thread...OK
EQ support: no
Scheduling '/home/falktx/Personal/Muzyks/Kits/SFZ/Shrine Piano v1.3/SFZ/The Shrine Piano v1.3.sfz' (Index=0) to be loaded in background (if not loaded yet).
Carla Bridge Ready!
Loading sfz file '/home/falktx/Personal/Muzyks/Kits/SFZ/Shrine Piano v1.3/SFZ/The Shrine Piano v1.3.sfz'...The opcode 'label_cc15' is unsupported by libsfz!
The opcode 'label_cc16' is unsupported by libsfz!
The opcode 'label_cc64' is unsupported by libsfz!
Stopping disk thread...OK
The opcode 'sustain_sw' is unsupported by libsfz!
Starting disk thread...OK
Loading sfz instrument ('/home/falktx/Personal/Muzyks/Kits/SFZ/Shrine Piano v1.3/SFZ/The Shrine Piano v1.3.sfz',0)...OK
Caching initial samples...OK
EQ support: no
OK
Plugin binary '/home/akik/.sounds/sfz/mf-taiko-drum.sfz' doesn't exist on this filesystem, let's look for it...
Found it! :)
starting plugin bridge, command is:
/usr/lib/lv2/carla.lv2/carla-bridge-native "SFZ" "/home/falktx/Personal/Muzyks/Kits/SFZ/mf-taiko-drum-ogg/mf-taiko-drum.sfz" """" 0
CarlaThread with realtime priority successful
Starting disk thread...OK
EQ support: no
Stopping disk thread...OK
Starting disk thread...OK
EQ support: no
Scheduling '/home/falktx/Personal/Muzyks/Kits/SFZ/mf-taiko-drum-ogg/mf-taiko-drum.sfz' (Index=0) to be loaded in background (if not loaded yet).
Carla Bridge Ready!
Loading sfz file '/home/falktx/Personal/Muzyks/Kits/SFZ/mf-taiko-drum-ogg/mf-taiko-drum.sfz'...OK
Loading sfz instrument ('/home/falktx/Personal/Muzyks/Kits/SFZ/mf-taiko-drum-ogg/mf-taiko-drum.sfz',0)...OK
Caching initial samples...Stopping disk thread...OK
Starting disk thread...OK
EQ support: no
OK
Trying to start carla-plugin using "/usr/lib/lv2/carla.lv2//resources//carla-plugin"
LRDF Support not available (LADSPA-RDF will be disabled)
Carla 1.9.9 (2.0-beta7) started, status:
  Python version: 3.4.3
  Qt version:     4.8.6
  PyQt version:   4.10.4
  Binary dir:     /usr/lib/carla
  Resources dir:  /usr/share/carla/resources
ALL OK!
Using Carla plugin embedded, waiting for it to be ready...
Done!
lv2ui_extension_data("http://lv2plug.in/ns/extensions/ui#idleInterface")
Trying to start carla-plugin using "/usr/lib/lv2/carla.lv2//resources//carla-plugin"
LRDF Support not available (LADSPA-RDF will be disabled)
Carla 1.9.9 (2.0-beta7) started, status:
  Python version: 3.4.3
  Qt version:     4.8.6
  PyQt version:   4.10.4
  Binary dir:     /usr/lib/carla
  Resources dir:  /usr/share/carla/resources
ALL OK!
Using Carla plugin embedded, waiting for it to be ready...
Done!
lv2ui_extension_data("http://lv2plug.in/ns/extensions/ui#idleInterface")
```

@aki-k please do the same - run ardour, with the path to the project, in the command-line and paste the output of the command-line here.
Thanks

**Comment by aki-k** [comment] 2018-08-09 18:17
Could it be something to do with my output missing the "Carla 1.9.9 (2.0-beta7) started, status:" lines?

**Comment by codecollider** [comment] 2018-08-10 14:20
> Could it be something to do with my output missing the "Carla 1.9.9 (2.0-beta7) started, status:" lines?

Edit: Also getting this error now right after a reboot and starting Ardour from the terminal:

Failed to load a plugin, error was:
Timeout while waiting for a response from plugin-bridge
(or the plugin crashed on initialization?)

I get exactly the same with Ardour 5.12 and only one midi track.

**Comment by falkTX** [comment] 2018-08-10 14:43
> Failed to load a plugin, error was:
> Timeout while waiting for a response from plugin-bridge
> (or the plugin crashed on initialization?)

haha! this is the key.

the bridge that was supposed to have loaded the linuxsampler instance failed to load, or crashed.

**Comment by aki-k** [comment] 2018-08-14 13:51
Do you have an idea where to look for this timeout problem or if you have an idea for a quick fix? Linuxsampler lv2 on a midi track doesn't seem to give this problem.

**Comment by falkTX** [comment] 2018-08-14 13:53
Are you able to build carla yourself, from git?
there is something I can do, disabling the bridging of linuxsampler altogether, so it never fails to load.
(might get muted though)

in any case, I have started the work to remove linuxsampler and replace it with something else...

**Comment by aki-k** [comment] 2018-08-14 13:54
Sure I can try. I've compiled a lot of things before in my life.

**Comment by falkTX** [comment] 2018-08-14 13:57
Actually, there is a quick experiment you can do without compiling.
Run this:
```
sudo rm /usr/lib/carla/carla-bridge-native
```
This remove the bridging for native plugins/code, so linuxsampler cant as bridge anymore and will always be local.
Let me know how that works for you.

**Comment by aki-k** [comment] 2018-08-15 09:32
I removed carla-bridge-native, but it didn't help in Carla-rack sfz usage. As you said the soundfont would still appear in Carla-rack but it was muted. Should I compile it myself from GitHub?

**Comment by falkTX** [comment] 2018-08-15 09:45
No, that won't solve anything.
The reason carla runs linuxsampler as bridge is precisely because of this mute issue.
Seems linuxsampler is not fit to be run as a plugin.
My initial tests with sfzero were quite sucessful, and I already started the move process.

if you build carla from git once, you will be ready to test early once I finalize the code for it.

**Comment by falkTX** [comment] 2018-08-18 18:06
Carla latest git code has the new built-in sfzero code, no longer using linuxsampler.

With this change, direct support for GIG files is now gone.
I will add backwards compatibility with existing projects, by loading linuxsampler as plugin.
Hopefully it works out...

**Comment by falkTX** [comment] 2018-08-18 18:06
PS: I will update the kxstudio repo packages after that backwards compatibility is in place.

**Closed by falkTX** 2018-08-18 18:06 UTC
Labels: bug

**Comment by DeathBush19** [comment] 2022-04-05 15:04
Here's the saved Ardour session which on load has an empty Carla-rack on the Taiko Drum midi track.

https://transfer.sh/16jLm4/carla-rack-empty-3.tar.gz

I've used these two SFZs that are stored in $HOME/.sounds/sfz:

The Shrine Piano:
https://musical-artifacts.com/artifacts/460

Somebody could give a drive share link for the Shrine piano that is now unvaible?

**Comment by aki-k** [comment] 2022-04-11 18:31
@DeathBush19 

I uploaded the Shrine Piano here:

https://transfer.sh/pqQRbR/Shrine_Piano_v1.3.zip

It'll be available for 10 or 14 days.
