### ISSUE TITLE
Carla 2.5.0 on Linux fails to load Windows VST dlls

### ISSUE THREAD

**Issue by korincatnip** [falkTX/Carla#1652] opened 2022-07-23 12:10 UTC
I am using Carla within Renoise to bridge some Windows VSTs, using v2.4.3 up until Wednesday this week when I updated to 2.5.0. 

Since then, when I try to add a Windows VST plugin I get the message **"Failed to load plugin - Timeout while waiting for a response from plugin-bridge (or the plugin crashed on initialization?)"** - this happens whether I use it within renoise or standalone.

LADSPA. LV2, and Linux VSTs are all unaffected. I couldn't see anything in the Terminal that might be useful, but happy to pass on any info that might be helpful!

**Comment by falkTX** [comment] 2022-07-23 12:29
Duplicate of #1642 I will look into soon.

**Closed by falkTX** 2022-07-23 12:29 UTC
