### ISSUE TITLE
qtractor & carla.lv2 as sfz player: 2nd instance not audible

### ISSUE THREAD

**Issue by suedwestlicht** [falkTX/Carla#324] opened 2015-11-14 21:42 UTC
I have a Qtractor session with 2 midi tracks. On each there's Carla as a sfz player. Works ok. But when I save the session and reload it, only one track is audible. Both Carlas load their soundfonts. But on one of them I have to remove and load the soundfont again to make it audible.

I can't attach a qtz file, so please get it from http://www.marzen.de/tmp/test_carla.qtz
You have probably change paths and soundfonts, but you got the idea.

**Comment by falkTX** [comment] 2015-12-29 12:52
I'm closing this one as it's a duplicate of #250 
See that bug for more details.

**Closed by falkTX** 2015-12-29 12:52 UTC
Labels: bug, duplicate
