### ISSUE TITLE
Cannot run Carla_2.0-beta6-linux64

### ISSUE THREAD

**Issue by Sir-hennihau** [falkTX/Carla#627] opened 2018-05-11 09:21 UTC
Hi,
I want to use the binary from http://kxstudio.linuxaudio.org/Applications:Carla , Linux 64 Bit.

I tried after downloading and extracting

chmod +x Carla
chmod +x CarlaControl

Then I tried executing the binary with ./Carla and received:

> Carla: loadlocale.c:130: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.
> Aborted
> 

What am I missing or doing wrong?

Running on Ubuntu 18.04

BTW: Is there somewhere a complete guide to install carla?

Greetings, keep up the good work.

**Comment by falkTX** [comment] 2018-05-12 09:49
This is a duplicate of #623
One of the dependencies used by Carla static builds needs updating.
Nothing you can do on your side to fix it, sadly.

To build on your version of Carla, see https://github.com/falkTX/Carla/blob/master/INSTALL.md
For Ubuntu, Carla is available on the KXStudio repos.

**Closed** 2018-05-14 18:04 UTC
