### ISSUE TITLE
Carla might crash Reaper with JUCE Assertion failure in juce_Thread.cpp:43

### ISSUE THREAD

**Issue by codecollider** [falkTX/Carla#1136] opened 2020-05-17 20:32 UTC
Not 100% if it's a Carla bug, but I reproduced it several times with Carla and without Carla Reaper does not crash. 

Reaper is crashing sometimes when closing a project file via the X symbol on the Reaper project tab (top left side). It asks me to save the project and when I hit "no" Reaper freezes. This happens with an empty Carla Rack plugin on the master bus. When removing Carla Reaper closes the project without crashing. Reproduced it in one larger project several times. With a new project I couldn't reproduce it. 

In the terminal I have these last lines:
JUCE Assertion failure in juce_Thread.cpp:43
Killed

"JUCE Assertion failure in juce_Thread.cpp:43" always comes up when crashing.

**Comment by falkTX** [comment] 2020-05-17 21:03
Is this on Linux?
Are you using Carla Rack or Patchbay plugin version? If Patchbay, try the Rack version and see if the same issue still happens. This will help to clarify the issue. Thanks

**Comment by codecollider** [comment] 2020-05-17 22:08
Yup, Debian 10. Just checked and it happens with Carla Rack and also with Patchbay. 
Sometimes the screen looks like this:

https://i.imgur.com/6cfXoxW.png

Cheers
Marco

**Comment by falkTX** [comment] 2020-05-18 01:36
Are you able to build carla?
We could try an experiment and build carla without juce, just to see what happens. it is a simple `make USING_JUCE=false`, assuming you have all dependencies in place.

**Comment by codecollider** [comment] 2020-05-18 18:43
I can give it a try, but I can first try to reproduce it with a smaller project. Maybe you can reproduce it then on your system if that makes sense. I also would need some description how to build it.

**Comment by codecollider** [comment] 2020-05-18 21:31
It happens already with just Carla (empty) on the master using Reaper V 6.10. Can you test it?
Here's a small vid. I didn't start Reaper from the terminal but if you do you get sigterm and the juce error. From the former test it's still in the terminal:

https://vimeo.com/420076653

**Comment by akimaze** [comment] 2020-07-04 18:54
Hi, I think that I can reproduce this issue also in LMMS (on Linux Mint) sometimes when I add Carla Rack (for example with Helm LV2) and next when it plays just drag'n'drop other instrument to this track. LMMS crashes/hangs and in terminal last line is 
`JUCE Assertion failure in juce_Thread.cpp:43`

The error does not always occur, it seems that it is easier to make crash in a larger project.

**Comment by akimaze** [comment] 2020-07-04 21:07
Sometimes it's enough to just delete the track with Carla Rack instrument.

**Comment by akimaze** [comment] 2020-07-18 18:16
@falkTX I made more tests Carla compiled with `make USING_JUCE=false` works OK in LMMS.

But build without `USING_JUCE=false` crashes/hangs LMMS some times with `JUCE Assertion failure in juce_Thread.cpp:43` in terminal.

Steps to reproduce:
1. add Carla Rack to track
2. remove Carla Rack track

**Comment by falkTX** [comment] 2020-07-18 19:59
I forgot about this, and it missed the 2.2-RC1 release.
But good that you tested without JUCE, makes it clear that something regarding JUCE management is the cause of the issue.

**Comment by falkTX** [comment] 2020-07-20 01:36
Working fine with LMMS here, at least with 2 times everything was fine.
A few tries with reaper and all was fine too.

@akimaze you tried with the tagged 2.2.0-RC1 release, right?

**Comment by akimaze** [comment] 2020-07-22 17:05
@falkTX Sorry for the delay, I used develop branch (I just cloned carla repository, devel branch 6a783076e89b878339190aeb60477d21a9596068 18.07.2020 v2.2.0-RC1). 

Compiled by:
```
make -j12
sudo make install PREFIX=/usr
```

 I used current LMMS master branch (23242b9529b759ae1f6d51c756ca9ea1ddaee2d4). Audio output is set to SDL( buffer: 2048).

LMMS compiled by:
```
git clone https://github.com/LMMS/lmms.git
git submodule update --init --recursive
mkdir build
cd build 
cmake .. -DCMAKE_INSTALL_PREFIX=../target/
make -j12
./lmms
```
Today to crash I needed:
1. Drag Carla Rack
2. Remove Carla Rack track
3. Drag Carla Rack again
4. Remove Carla Rack track -> crash with "JUCE Assertion failure in juce_Thread.cpp:43" in terminal.

This is Linux Mint 19.3 Tricia, Ryzen 3700X

**Comment by akimaze** [comment] 2020-07-22 17:26
I also compiled lmms with `cmake .. -DCMAKE_INSTALL_PREFIX=../target/ -DCMAKE_BUILD_TYPE=Debug`

This is the output of gdb maybe will help you:

[gdb_carla_lmms.txt](https://github.com/falkTX/Carla/files/4961457/gdb_carla_lmms.txt)

**Comment by falkTX** [comment] 2020-08-17 16:56
Likely fixed in 7dc9e8fce4ad77051c38d788c4e21886ef185db4 now, testing would be greatly appreciated.

**Comment by falkTX** [comment] 2020-09-01 10:42
Ardour had a similar issue, so things might be fixed now.

**Closed by falkTX** 2020-09-01 10:42 UTC
Labels: bug

**Comment by akimaze** [comment] 2020-09-01 16:11
@falkTX Now everything works in LMMS :) I think it can be closed if @codecollider confirm that Reaper works too.
