### ISSUE TITLE
Getting Library not found for VST under Wine

### ISSUE THREAD

**Issue by tetebueno** [falkTX/Carla#1064] opened 2020-03-27 12:47 UTC
Hi, I'm working under Linux with Carla version 2.0.0 and when I ask Carla to scan for plugins it doesn't find a specific VST to be run on Wine. I tried also in command line the following to see the error:

```
/usr/lib/carla$ ./carla-bridge-win64.exe "VST2" ~/.wine/drive_c/Program\ Files/Steinberg/VSTPlugins/Plugin\ Alliance/bx_cleansweep\ V2.dll "bx_cleansweep V2"
err:winedevice:ServiceMain driver L"WineBus" failed to load
libjack.so.0 loaded sucessfully!
err:module:import_dll Library MSVCP140.dll (which is needed by L"Z:\\home\\user\\.wine\\drive_c\\Program Files\\Steinberg\\VSTPlugins\\Plugin Alliance\\bx_cleansweep V2.dll") not found
err:module:import_dll Library VCRUNTIME140.dll (which is needed by L"Z:\\home\\user\\.wine\\drive_c\\Program Files\\Steinberg\\VSTPlugins\\Plugin Alliance\\bx_cleansweep V2.dll") not found
err:module:import_dll Library api-ms-win-crt-runtime-l1-1-0.dll (which is needed by L"Z:\\home\\user\\.wine\\drive_c\\Program Files\\Steinberg\\VSTPlugins\\Plugin Alliance\\bx_cleansweep V2.dll") not found
err:module:import_dll Library api-ms-win-crt-math-l1-1-0.dll (which is needed by L"Z:\\home\\user\\.wine\\drive_c\\Program Files\\Steinberg\\VSTPlugins\\Plugin Alliance\\bx_cleansweep V2.dll") not found
err:module:import_dll Library api-ms-win-crt-string-l1-1-0.dll (which is needed by L"Z:\\home\\user\\.wine\\drive_c\\Program Files\\Steinberg\\VSTPlugins\\Plugin Alliance\\bx_cleansweep V2.dll") not found
err:module:import_dll Library api-ms-win-crt-stdio-l1-1-0.dll (which is needed by L"Z:\\home\\user\\.wine\\drive_c\\Program Files\\Steinberg\\VSTPlugins\\Plugin Alliance\\bx_cleansweep V2.dll") not found
err:module:import_dll Library api-ms-win-crt-filesystem-l1-1-0.dll (which is needed by L"Z:\\home\\user\\.wine\\drive_c\\Program Files\\Steinberg\\VSTPlugins\\Plugin Alliance\\bx_cleansweep V2.dll") not found
err:module:import_dll Library api-ms-win-crt-heap-l1-1-0.dll (which is needed by L"Z:\\home\\user\\.wine\\drive_c\\Program Files\\Steinberg\\VSTPlugins\\Plugin Alliance\\bx_cleansweep V2.dll") not found
err:module:import_dll Library api-ms-win-crt-convert-l1-1-0.dll (which is needed by L"Z:\\home\\user\\.wine\\drive_c\\Program Files\\Steinberg\\VSTPlugins\\Plugin Alliance\\bx_cleansweep V2.dll") not found
err:module:import_dll Library api-ms-win-crt-utility-l1-1-0.dll (which is needed by L"Z:\\home\\user\\.wine\\drive_c\\Program Files\\Steinberg\\VSTPlugins\\Plugin Alliance\\bx_cleansweep V2.dll") not found
err:module:import_dll Library api-ms-win-crt-time-l1-1-0.dll (which is needed by L"Z:\\home\\user\\.wine\\drive_c\\Program Files\\Steinberg\\VSTPlugins\\Plugin Alliance\\bx_cleansweep V2.dll") not found
Plugin failed to load, error was:
Z:\home\user\.wine\drive_c\Program Files\Steinberg\VSTPlugins\Plugin Alliance\bx_cleansweep V2.dll: error code 126: Module not found.
```

After realizing there were missing libraries I tried installing them in the default WINEPREFIX (`~/.wine`). I'm showing an example with one specific library (vcruntime140.dll):

```
~$ ls -lh .wine/drive_c/windows/system32/ | grep vcruntime140
-rw-rw-r-- 1 user group 1,1K may 20  2018 vcruntime140.dll
```
```
~$ cat .wine/user.reg | grep -B 20 vcruntime140
    [...]
[Software\\Wine\\DllOverrides] 1584990048
    [...]
"vcruntime140"="native,builtin"
```

After this, the result is the same, none of the libraries are found. Maybe it's using another WINEPREFIX I'm not aware of. I don't know.

Is there anything else I can check or any further debug info I can check/gather?

Thanks!

P.S.: some more system info:

```
~$ uname -a
Linux Data 4.15.0-91-lowlatency #92~16.04.1-Ubuntu SMP PREEMPT Fri Feb 28 16:07:55 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
~$ apt-cache policy carla-bridge-win64
carla-bridge-win64:
  Installed: 2:2.1~alpha2+git20190321
  Candidate: 2:2.1~alpha2+git20190321
  Version table:
 *** 2:2.1~alpha2+git20190321 500
        500 http://ppa.launchpad.net/kxstudio-debian/apps/ubuntu trusty/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by falkTX** [comment] 2020-03-30 16:20
winetricks will be very useful here.

sorry I cant give support here, the issue is with wine and windows libraries, which is out of scope of this project.
I need to keep issues on this bug tracker on topic.

**Closed by falkTX** 2020-03-30 16:20 UTC

**Comment by tetebueno** [comment] 2020-03-30 18:20
No problem.

Cheers, and thanks for this awesome project.
