### ISSUE TITLE
removing some plugins on carla patchbay makes crashes

### ISSUE THREAD

**Issue by Houston4444** [falkTX/Carla#185] opened 2015-01-06 12:32 UTC
Carla crashes when I remove plugins in carla patchbay.
Launching carla-patchbay, if I remove one plugin, carla-patchbay crashes.
Lauching carla, If I put carlaPatchbay plugin (internal), and in this carla-patchbay plugin, I remove one plugin, Carla crashes, carlaPatchbay's GUI stays but is unusable.

It doesn't always crashes and it doest really depends of which plugin is removed.
It seems to crash more if plugin settings have been changed, but I really can't find in which case it crashes.

On crash, konsole always says: Segmentation fault (I am not sur of translation)

and some times, something as this:

Carla assertion failure: "engine != nullptr" in file CarlaEngineGraph.cpp, line 984

or

Carla assertion failure: "pData->pipeRecv != INVALID_PIPE_VALUE" in file ../utils/CarlaPipeUtils.cpp, line 972

**Comment by ViktorNova** [comment] 2015-01-07 00:47
I can confirm that this has happened to me many times as well (when removing plugins)

**Comment by falkTX** [comment] 2015-01-07 03:26
Note that this is a duplicate of #166 but since this one is so serious I'll let the 2 bugs open until I fix them. I'm working on it now.

**Closed** 2015-02-14 15:19 UTC
Labels: bug, duplicate
