### ISSUE TITLE
VST plugin UI display issue

### ISSUE THREAD

**Issue by danboid** [falkTX/Carla#420] opened 2016-09-27 19:06 UTC
I'm running the latest Carla build from the KX repos (1.2.4) under Ubuntu MATE 16.04 x64.

When I open the UI for a (Linux native VSTi) plugin, I get a blank window and the plugin UI that should be within the empty window is displayed separately, aligned to the top left of the main Carla window and not within a window hence unmovable. This occurs for all the VSTi plugins I've tried.

**Comment by falkTX** [comment] 2016-11-13 09:46
Use 'carla-git' package instead of 'carla', and let me know if the issue is still present.

**Comment by falkTX** [comment] 2020-04-11 14:55
Closing since this refers to 1.x series, no longer supported.

**Closed by falkTX** 2020-04-11 14:55 UTC
Labels: needs more info
