### ISSUE TITLE
nanoKONTROL2 crashes Carla

### ISSUE THREAD

**Issue by BakeGate** [falkTX/Carla#1111] opened 2020-04-30 12:38 UTC
Hi, having an issue where Carla crashes whenever I try to plug the nanoKONTROL2 to midi-in in patchbay mode. Tried older versions, tried to launch Carla in admin mode, didn't change anything.

**Comment by BakeGate** [comment] 2020-04-30 19:31
Okay so the problem seems to come from the fact that it's the last in the midi devices list. I tried with other devices and the last one always crashes Carla.

**Comment by falkTX** [comment] 2020-04-30 20:10
So when you connect something to the last MIDI port in the "external" section, carla crashes, is that it?

**Comment by BakeGate** [comment] 2020-04-30 20:59
Yes, and also I can't seem to find where the log file is, if there's one.

**Comment by Francefire** [comment] 2020-05-09 19:02
I managed to fix it by plugging another MIDI to my computer, then refresh, and the MIDI that made Carla crash will now be linked and you will be able to delink or link it without crashing. If you don't have two midi devices lying arround, just add a rtpMidi session enable it and refresh Carla canvas

**Comment by falkTX** [comment] 2020-05-15 18:54
I cannot reproduce this, maybe already got fixed unintentionally since quite a few things changed in the backend.
I will post a updated build so you can verify if that is the case for you too.
64bit is fine right?

**Comment by Francefire** [comment] 2020-05-15 22:11
Just tried the version you provided, and it works. No crash on linking a Midi Device. I'll get back to you if it ever happen again. Thank for the quick fix

**Comment by falkTX** [comment] 2020-05-15 22:33
that is great to hear, thanks for testing.
I will close the issue then. Feel free to reopen if it happens again!

**Closed by falkTX** 2020-05-15 22:33 UTC
Labels: bug, can't reproduce, needs testing
