### ISSUE TITLE
Carla unable to find the program entry point  __gxx_personality_sj0 could not be located in the dynamic link library libstdc++-6.dll

### ISSUE THREAD

**Issue by sunny8484** [falkTX/Carla#1132] opened 2020-05-15 16:52 UTC
Anyone else have the same issue?

![Carla_o5w709a0Vr](https://user-images.githubusercontent.com/18023206/82074415-4cf95880-970d-11ea-845c-599889cbc812.png)
![csrss_qFjpkF8be9](https://user-images.githubusercontent.com/18023206/82074452-5c78a180-970d-11ea-87c8-781942dcd657.png)

**Comment by falkTX** [comment] 2020-05-18 01:53
First time I see this.
Sorry, I do not know how to solve it.

**Comment by andlabs** [comment] 2020-06-22 02:24
You will need to distribute libstdc++-6.dll included in your MinGW distribution with Carla, or build Carla with `--static-libstdc++`. I don't know if doing the latter will cause problems when loading plugins or not. Yes, that's right, `--static` is not sufficient to statically link binaries on Windows, because the MinGW C/C++ runtime is still linked dynamically. (You may also need libgcc.dll or `--static-libgcc` in addition to the above; I'm not sure).

What MinGW distribution do you use to build your binaries? I have to use the exact one you use; if I just copy the requisite DLL from my MinGW-w64 (via MSYS2) distribution, it still can't find the relevant symbol because the exception handling models do not match.

Yes, this is a mess.

My advice for reproducing this yourself is to try running your Carla binary disributions on a fresh Windows VM without any other software previously installed.

**Comment by falkTX** [comment] 2020-06-22 02:27
Carla binaries are fully static, only python I grab from mxe which uses shared libs. Those shared libs are inside the self-contained executable, otherwise they would not even run.
For v2.2, I will try to build python myself, which then I can make static as well and thus fix this issue.

**Comment by andlabs** [comment] 2020-06-23 04:59
All right.

I can reproduce this with 2.1, but 2.0 works fine. I also tried building Carla myself on Windows directly with MSYS2 and ran into some problems; I'll be filing bugs about those soon.

**Comment by falkTX** [comment] 2020-06-23 10:17
Carla 2.0 binaries used official python and pyqt binaries (from python.org and riverbank respectively)
On 2.1, I changed to mxe binaries.
The reason for the change is that I need to build a couple of things against python and qt, and for that I need to use mingw-built libraries.
But building python under mingw is not an easy step, mxe has over 100 patches.. still, I am working on a setup that will allow me to do just that.

**Comment by sound8** [comment] 2020-10-29 18:43
I am still experiencing the same thing when trying to use Carla 2.2.0 in Windows 7 Pro (64Bit).

I don't experience this with any other programs.
Does anyone know if this is a Windows issue or a Carla issue?
I think I have all the C++ packages installed does anyone know what package this libstdc++-6.dll file belongs to.
I have seen online random websites that allow you to download this specific file but don't want to install this way, has to be a part of some kind of official package to download and install?

Just wondering if a solution was ever found for this?
Shame I have not been able to use Carla for almost a year now.

**Comment by sound8** [comment] 2020-11-01 16:19
I apologize, I do not know anything about all the coding languages mentioned in above discussion.
Is there a specific MinGW or Python kit that would provide this libstdc++-6.dll file that Carla 2.2.0 would then be able to access or is this more of an internal coding that needs to be fixed?
I tried downloading some MinGW packages but there seem to be different versions / branch offs / etc.
I also seem to keep finding online installers of MinGW where I am looking to just have a full installer for Windows 7.

Very strange, I would imagine Windows 7 is still a used OS by many, do all Windows 7 users experience this error, or is it just a lucky few?

**Comment by falkTX** [comment] 2020-11-01 17:57
I might just be you have some dlls installed in your windows dir, that are used in preference of carla custom ones.

**Comment by sound8** [comment] 2020-11-01 21:27
@falkTX 
Thank you very much for your response.
It wasn't that, but I guess I just needed to be in your presence to absorb some of your knowledge to figure it out (the idea litterally came to me a couple minutes after I read your response :)

Don't know if this is the exact reason but, Carla is in essence a standalone program, so with past versions I would test it out on my D:\ drive and not my C:\ and it would always work.

With newer releases I started getting this error when trying to test (didn't know coding changed as much as it did).
I assume it was because you began a different coding approach which no longer allows for this it to be on a different drive?
Anyways the main thing is I unzipped and ran it on my C:\ drive and it works!!!!
Oh, man I am so happy right now!

Well if there is a benefit to this issue it is that at least I had the opportunity to say thank you for all the work that you provide for everyone, pretty amazing.
Keep up the great work!

**Comment by sound8** [comment] 2020-11-10 13:14
Not sure if interested, but I figured out some more information on what was causing this error.
I was wrong about it being on a different drive that is not what was causing the issue.
I am using Windows 7 (64Bit) and I was trying to run Carla (32Bit) that is what was causing the issue.
The other day when I got it to work, I loaded the 64 Bit version of Carla which opened perfectly.
When I go to run the 32 Bit version that is when that error comes up about the libstdc++-6.dll file.
I tried this on two machines and they both produced the same results.

Other strange test I did is...
If I open up Carla 64, and then while that version is open, I try also running Carla 32 then it actually opens with no error.

Also tested...
Copying the libstdc++-6.dll files from the 64Bit version into the 32Bit just to see if that had anything to do with it but it does not, the 32Bit version still produced the error.


Is Carla specifically designed to run 
32 Bit version on a 32 Bit Windows OS 
and 
64 Bit Carla on a 64 Bit Windows OS only?

Has anyone been able to get Carla 32 to run on Windows 64?

Either way the main thing is that I was at least able to get it to open / work in 64Bit and so far it seems to work (be able to load) 32Bit VSTs so hopefully I don't have to use Carla 32 in the future.

Just figured I would share this information just in case someone experiences this in the future and is looking for an answer possibly why this is happening.

Thank You

**Comment by amurzeau** [comment] 2020-11-22 19:08
I get this error too.

`__gxx_personality_sj0` is when using SJLJ exceptions, but Carla and Qt seems compiled with DWARF exceptions instead (except for `carlastyle.dll`).
Is `carlastyle.dll` compiled with the same compiler ?

This can be checked with Dependency Walker.
in the root folder of Carla, `libstdc++6.dll` and Qt requires `__gxx_personality_v0` instead, and there is `libgcc_s_dw2-1.dll` instead of `libgcc_s_sjlj-1.dll`.

**Comment by falkTX** [comment] 2021-02-17 12:56
Fixed in 2.3 release.

**Closed by falkTX** 2021-02-17 12:56 UTC
Labels: bug, can't reproduce, needs external work
