### ISSUE TITLE
Carla Usability PluginGUI access from patchbay broken

### ISSUE THREAD

**Issue by ahellquist** [falkTX/Carla#1108] opened 2020-04-28 15:16 UTC
A long time ago every plugin that had their own GUI that was easily accessible both from the Plugins tab as well as the Patchbay tab.

Later, for some reason some of the plugin GUIs  was accessible from both tabs but some only from the Plugins tab.

Now, in latest Ubuntu Studio 20.04 Accessing Plugin GUIs are not possible from the patchbay at all.

For many years I have only used the patchbay view since thats were I can patch, remove, add and access the generic and custom GUIs. Specially if I'm on tour and need to do some adjustments.
I use Carla Presets that loads all my plugins and patches them accordingly.

Now, if I have to switch view to get a huge list of plugins in a random order with minimal knobs and text, I can probably find the plugin after a while but I am losing context and will have to abandon my main view, (patchbay) for no reason just to open a GUI.

This is especially hard on modern highDPI laptops where things get really tiny. The canvas in the patchbay can be zoomed and adjusted to once taste regardless of DPI or amount of plugins.

Is the Carla that ships with Ubuntu Studio 20.04 broken or is there a setting I can change to get my plugin GUIs easy accessible again ?
If this is caused by something Ubuntu Studio devs have done to their setup, I should address the issue to them

**Comment by falkTX** [comment] 2020-04-28 15:27
I changed how carla handles the patchbay plugin integration in JACK mode to rely on JACK metadata instead of local caching the values (which was prone to errors from time to time).
This new method requires a version of JACK that has working meta-data support though. Either JACK1 or JACK2 >= 1.9.13

The issue is not there when using carla in patchbay mode (instead of multi-client)

**Comment by ahellquist** [comment] 2020-04-28 15:54
@falkTX Thanks for the quick response. Are we talking about the same thing here. I am only talking about the behavior when running Carla as a standalone application with multiple plugins loaded.
Patchbay in my first note in this issue is only related to the **Patchbay tab** in standalone Carla.

IE using Carla Patchbay is out of this scope. Just to make sure we are on the same page.

I am only looking for a way to be able to launch the plugin GUIs **without having to change the Carla interface to show the "Rack with all plugins"** but just double click the plugin of choice on the Carla Standalone Application -> Tab named "Patchbay" -> Plugin named "Pianoteq" (as an example)

**Comment by falkTX** [comment] 2020-04-28 15:58
Yes, I understand that.

When I say:
> The issue is not there when using carla in patchbay mode (instead of multi-client)

I am speaking about the engine mode.
There are 4 of them when using JACK as driver:
- single-client
- multi-client
- continuous rack
- patchbay

Under multi-client mode (the default), Carla can only interact with its own plugins in the patchbay tab when using a recent enough JACK2 version (or JACK1).
If the engine mode is set to patchbay, then this always works no matter what. BUT you then lose the option to arbitrarily connect plugins to other JACK clients

**Comment by ahellquist** [comment] 2020-04-28 19:00
Hi again

I tried the Patchbay mode but could not hook up my two keyboards and use the midi-split plugin to select what plugins my keyboards would feed since those features were not available in patchbay mode.
All my presets were not of any use since they contains stuff that patchbay mode cannot use.

For me at this moment suddenly and very unexpected Ardour seems to be a better platform to host plugins in a versatile way and being able to quickly launch their respective GUIs. Like I imagine Mainstage works (Haven't use that, only heard of that being a common live gig software)

Are any of the other 2 modes useful for my needs, IE Having a patchbay canvas with lots of stuff AND having access to those GUIs without the need to switch away ?

Thanks

**Comment by falkTX** [comment] 2020-05-09 10:53
there is a midi channel filter plugin which you can use. (though you need many of them vs a single midi-split plugin, I know..)
I know the limitation is annoying, just quite tricky to fix, but I will do it at some point.

I could try to find a way around this, but seems quite wasteful since what is there already works, it just assumes you have a recent enough jack version.
I will ping the UbuntuStudio lead person to ask for a jack version backport.

I am closing the ticket, since I do not actually plan to go back to the "racy" behaviour of past releases, so should not leave hope for that.

**Closed by falkTX** 2020-05-09 10:53 UTC

**Comment by ahellquist** [comment] 2020-05-09 14:32
No worries.

I am really grateful for everything you do and if you plan to adress the
limitation some time in the future I am ok. The thing with Linux in general
that makes my usability issues even worse is the lack of support for high
dpi screens (especially on laptops) and that makes my gui issues less than
great even if I switch to the Rack view.. I will probably just live with
the regression until there is a way around it.

Keep up the good work.

Regards, Anders

**Comment by falkTX** [comment] 2020-05-09 15:10
tbh I dislike the general approach of high-dpi screens. personally find it a waste of CPU/GPU resources, since we have to render everything at twice the size.
that said, I understand some people do like it, and also new hardware comes with high-dpi without giving user the choice. I already started the work for high-dpi in carla, just that it does not get much attention. just report the issues you see regarding it and i will fix them if I can.
