### ISSUE TITLE
resize carla-rack and carla-patchbay plugins

### ISSUE THREAD

**Issue by rhetr** [falkTX/Carla#261] opened 2015-05-19 15:51 UTC
i noticed that the internal carla-rack and carla-patchbays are different from the lv2/vst versions. I'd like to use the lv2 versions for increased interoperability in saving presets, because they don't have the sidemenu and because they don't open maximized in i3wm, but one thing that's stopping me from doing that is the windows can't be resized at all. This is acceptable for carla-rack but not for a patchbay, because it is incredibly difficult to actually find the location of an added plugin on the patchbay.

**Comment by falkTX** [comment] 2015-05-19 15:55
This is caused by the embedding.
If you load carla-lv2 as external UI there won't be such issues.

Sadly no host provides options to select which UI to use.
For now you can edit the carla's manifest.ttl and rename "http://kxstudio.sf.net/carla/ui-embed" to something else.

**Comment by falkTX** [comment] 2018-08-29 07:36
I am closing this issue, in favour of #693.
Target will be to display a tiny plugin UI that simple has a button to open the full one.
When we embed we lose drag&drop in some hosts, and keyboard shortcuts on all of them.
Plus resizing gets really tricky, and embed itself as well...
I will stop trying to make Qt embed into something else, that is not going to work well long term.

**Closed by falkTX** 2018-08-29 07:36 UTC
Labels: enhancement
