### ISSUE TITLE
Some plugins are loaded with wrong parameters when launching '.carxp' file

### ISSUE THREAD

**Issue by ranolfi** [falkTX/Carla#1171] opened 2020-06-13 05:34 UTC
I'm using Carla 2.1.1 on Arch Linux with Jack2 1.9.14.

I loaded some lv2 plugins, then saved a `.carxp` preset file. On my machine, Carla is launched automatically at user login.

It just so happens that, **sometimes** (often, actually), **one or more plugins are loaded with parameters that are different** than those in the _.carxp_ file. Which plugin(s), or when, appear to be completely random.  
Usually, but not always, it's one of either _[The Infamous Ewham](https://github.com/ssj71/infamousPlugins/tree/master/src/ewham)_, _[Noise repellent](https://github.com/lucianodato/noise-repellent/)_ or, more rarely, _[EQ10Q](http://eq10q.sourceforge.net/)_. Sometimes it's a combination of those.

In the case of _Noise repellent_, which I'm observing right now, when I click the wrench button in the interface and inspect the 'Parameters' tab, the plugin appears to be loaded with its default values, not those that I had set previously.

Stopping and restarting the Carla engine and reloading the _carxp_ preset does not fix the problem, no matter how many times I try. The only effective solution is to restart Carla itself, maybe a couple times, and pray that it works.

I've got the Carla source code checked out but don't know where to look; if you can point me in the right direction, I might be able to help in fixing this.

**Comment by Stazed** [comment] 2020-06-13 18:53
Can confirm this issue with latest git from the kxstudio repos. Upon further testing, in my case it appears to be a gui update issue. The .carxp values are loaded properly, but the gui does not reflect the file load changes. 

To force the gui to update, try right-click minimizing, then expand the plugin rack display. This seems to trigger a gui update to the correct .carxp values. You could also confirm if the .carxp values are loaded by running some sound through the effects.  Saving the settings, even when they are displayed incorrectly still saves the proper .carxp values that were loaded.

Also checked an earlier version, Carla 2.1.0, and it also exhibits the same behavior. Guessing that it might be some timing issue due to a change in QT thread processing??? Odd that it occurs with earlier versions of Carla, since this was not happening previously.

Very confusing and intermittent. Probably most users would not have noticed if they never opened the gui.

**Comment by ranolfi** [comment] 2020-06-15 21:57
@Stazed, thanks. Btw, is it possible to "right-click minimize" the linux version?

**Comment by Stazed** [comment] 2020-06-16 14:19
@ranolfi 

> is it possible to "right-click minimize" the linux version?

Yes. Perhaps I was not clear that I meant to minimize/expand the Carla rack display, not the gui itself. Right-click anywhere on the rack display for the plugin and a menu will show. The first item is "Minimize" or "Expand" depending on the current display status.

Upon further investigation, it appears that the gui refresh issue is only affecting the Carla generic gui in my case. For plugins that have custom guis, the custom gui always shows correctly, but the Carla generic will intermittently show defaults on file loading. For the generic gui, the minimize/expand seems to trigger a gui refresh. If you are having the problem with a custom gui, then it may be a different issue and the minimize/expand may not work.

**Comment by falkTX** [comment] 2020-06-26 06:55
@Stazed I think your issue is just something with the drawing operation of the generic GUI.
Seems like it is always 1 step behind the actual value that it should display. (relevant only for VST2/3 plugins)

For @ranolfi this is a bit different.
Will look into this before 2.2-RC1

**Comment by to7m** [comment] 2020-06-26 22:53
Ah, this is close to what's been happening on my setup.

On my setup, it currently only seems to be happening inside carla-patchbay plugins. If I try to load a .carxp file into a carla-patchbay, or try to load a .carxp file containing a carla-patchbay into Carla, then none of the parameters for plugins within the carla-patchbay are preserved. I used to have the problem with plugins directly loaded into Carla, but that hasn't been the case the last few times, whereas it has consistently been the case when a carla-patchbay plugin is involved. I find this consistently reproducable with Calf Equalizer 5 Band for example.

The .carxp file contains the parameters, they just don't get loaded by Carla. It's not a graphical thing; re-saving an opened file without touching the settings results in a very different .carxp file.

After loading a .carxp file from within a carla-patchbay, none of the values can be moved from GUI as they always snap back to a specific value. For example, all the frequency knobs in Calf Equalizer 5 Band snap to 10 Hz as soon as they're touched, and can't be moved back.

Nothing relevant appears in the Logs tab.

**Comment by falkTX** [comment] 2020-07-20 01:13
This might be fixed in 2.2-RC1 release, please confirm!
Pre-built binaries at https://github.com/falkTX/Carla/releases/tag/v2.2.0-RC1

**Comment by to7m** [comment] 2020-07-20 14:17
There are still some issues when the nesting level of patchbays within patchbays gets too high in some cases. So, if I open an inner patchbay (all using LV2 and not “internal”), its connections and plugins will be preserved, but if there is another inner patchbay within that inner patchbay, only the connections and not the plugin settings will be preserved. Another layer in, the connections are no longer preserved.

I'll do more testing (today hopefully) to see if this could cause practical problems. Maybe the excessive layering exposes an underlying bug? Thanks for the update!

**Comment by falkTX** [comment] 2020-07-20 14:30
hmm, I did not test that case at all haha.. there could be a bug around this yes.

**Comment by to7m** [comment] 2020-07-20 23:28
Sorry to confirm, but parameters are still lost in just one additional layer:((

In this example, I started a new Carla session, and added a single LV2 patchbay plugin. In this patchbay, I added a single Calf 5-band equaliser, and changed a parameter. After saving (from the patchbay's interface, to patchbayLV2_before_reopen) and opening it again, the parameter was still there, but after re-saving it from that re-opened file (to patchbayLV2_after_reopen), it was gone. Re-opening, re-saving, and re-opening the main Carla project causes the same problem. Running it from the terminal doesn't show any errors.

[examples.zip](https://github.com/falkTX/Carla/files/4950442/examples.zip)

There's also a possibly new problem where sometimes a plugin will freeze, but I haven't figured out how to reproduce that reliably yet...

**Comment by BlueMax** [comment] 2020-07-21 21:12
I've lost settings in 'Dragonfly Hall Reverb' from time to time. This seems to be fixed (at least it didn't occur for the last 7-8 start ups).

**Comment by ranolfi** [comment] 2020-07-22 03:39
The problem I originally reported here appears to be fixed in v2.2.0-RC1.

**Comment by falkTX** [comment] 2020-07-22 09:53
Cool. I will close this ticket then, as there are a couple of them open surrounding saved state, and would be nice to clean things up a bit
@to7m still need to see that nested parameter case, but I consider that a separate issue. please open up a new ticket if this is important to you, thanks

**Closed by falkTX** 2020-07-22 09:53 UTC
Labels: bug

**Comment by ranolfi** [comment] 2020-07-22 21:26
Thanks @falkTX. I also take this opportunity to leave a note on how much I appreciate the efforts you have put in developing this program. It's been extremely useful. I was watching some video presentations on the project's page and learned how it can do much more than I thought!

Regards.
