### ISSUE TITLE
Carla doen't load win plugins

### ISSUE THREAD

**Issue by rcspam** [falkTX/Carla#488] opened 2017-06-02 10:50 UTC
Since some days, it's impossible to load win plugins in carla:
logs:
```
usr/lib/carla/carla-bridge-win32.exe "VST2" "/home/rapha/VST/VSTPlugIns/Guitar Rig 4.dll" "Guitar Rig 4" 1315522356
WINE realtime scheduling hack enabled, realtime base priority has been set to 55
wineserver running SCHED_NORMAL
Plugin failed to load, error was:

No compatible plug-in format exists for this plug-in
```
But the same plugins start from carla-single or dssi-vst works very well.
I there something wrong in the carla config or a bug
Thanks

**Comment by rcspam** [comment] 2017-06-24 06:29
Hi FalkTX,
What is wrong in Carla.
VST plugins neither DSSI plugins doen't work anymore...
Can you help please

```
starting plugin bridge, command is:
/usr/lib/carla/carla-bridge-posix32 "DSSI" "/usr/lib/dssi/dssi-vst.so" "Guitar*Rig*4.dll" 6673
RemoteVSTClient: all cache files are up-to-date, not running scanner
DSSIVSTPlugin::instantiate(Guitar*Rig*4.dll)
DSSIVSTPluginInstance::DSSIVSTPluginInstance(Guitar*Rig*4.dll)
Returning file identifiers: sxaTjIq4CwzdoNGbRBFMYJhv
RemoteVSTClient: executing /usr/lib/dssi/dssi-vst/dssi-vst-server.exe Guitar*Rig*4.dll,sxaTjIq4CwzdoNGbRBFMYJhv
DSSI VST plugin server v0.986
Copyright (c) 2012-2013 Filipe Coelho
Copyright (c) 2010-2011 Kristian Amlie
Copyright (c) 2004-2010 Chris Cannam
Loading "Guitar Rig 4.dll"... done
Testing VST compatibility... Initialising Windows subsystem... done
cannot create dummy timer window
DSSIVSTPluginInstance::DSSIVSTPluginInstance(Guitar*Rig*4.dll) construction complete
DSSIVSTPlugin::configure(DSSI:SUPPORTS_CUSTOMDATA,)
DSSIVSTPluginInstance::configure(DSSI:SUPPORTS_CUSTOMDATA,)
client sized shm to 32
sized shm to 32, 2 inputs and 2 outputs
dssi-vst-server[1]: reset
Carla assertion failure: "fUniqueId == uniqueId" in file CarlaPluginBridge.cpp, line 1978, v1 6673, v2 6672
Carla Bridge Ready!
client sized shm to 4096
```

**Comment by rcspam** [comment] 2017-06-24 06:32
Hi FalkTX,
Is there something change in carla, impossible to open

**Comment by falkTX** [comment] 2017-06-24 09:25
why did you close this?

**Comment by rcspam** [comment] 2017-06-24 16:39
Sorry, just an error

**Comment by rcspam** [comment] 2017-06-24 16:40
Have you an idea about what happened.. Bug ? Config problem ?

**Comment by falkTX** [comment] 2017-07-02 08:35
I cannot reproduce this on either Ubuntu 14.04 or 16.04.
So likely just an issue on your side.
Can you run any windows binaries at all now?

How did you install carla, and which version?

**Comment by rcspam** [comment] 2017-07-02 08:57
This is my carla binaries from your ppa
```
$ apt policy carla-git 
carla-git:
  Installé : 2:1.9.7+git20170520v5.1
  Candidat : 2:1.9.7+git20170520v5.1
 Table de version :
 *** 2:1.9.7+git20170520v5.1 500
        500 http://ppa.launchpad.net/kxstudio-debian/ubuntus/ubuntu xenial/main amd64 Packages
        100 /media/rapha/HOME_TRUSTY/var/lib/dpkg/status
     2:1.9.7+git20170520v5 500
        500 http://ppa.launchpad.net/kxstudio-debian/gcc5/ubuntu xenial/main amd64 Packages
     2:1.9.7+git20170520 500
        500 http://ppa.launchpad.net/kxstudio-debian/apps/ubuntu trusty/main amd64 Packages
```
Launching windows VST from carla-single or dssi-vst works perfectly.
I have try to remove carla.conf... Same problem..
Binaries launch with wine works well, as well from carla-single and dssi-vst 

Here the log when i add win vst plugins 
![screenshot-carla](https://user-images.githubusercontent.com/10021906/27768484-0d9fa4f6-5f15-11e7-8313-29f7a96f4876.png)

**Comment by falkTX** [comment] 2017-07-02 09:07
maybe something got corrupted, I say remove all carla packages and reinstall them again.
also make sure 'wine ...' works, like "wine notepad".

**Comment by rcspam** [comment] 2017-07-02 09:14
Wine works like a charm.
Can you tell me the minimum carla install package to run win32/64 VST, i'll try to reinstall it
Just want to try without any useless packages

**Comment by falkTX** [comment] 2017-07-02 09:15
This is what I have:
```
ii  carla-bridge-linux32:i386                       2:1.9.7+git20170520v5.1                    i386         audio plugin host (linux32 bridge)
ii  carla-bridge-linux64                            2:1.9.7+git20170520v5.1                    amd64        audio plugin host (linux64 bridge)
ii  carla-bridge-win32                              2:1.9.7+git20170105                        amd64        carla win32 bridge
ii  carla-bridge-win64                              2:1.9.7+git20170105                        amd64        carla win64 bridge
ii  carla-bridge-wine32:i386                        2:1.9.7+git20170107.2                      i386         carla win32 bridge (wine DLL)
ii  carla-bridge-wine64                             2:1.9.5+git20160114                        amd64        carla win64 bridge (wine DLL)
ii  carla-data                                      2:1.9.7+git20170520v5.1                    all          audio plugin host (common data)
ii  carla-git                                       2:1.9.7+git20170520v5.1                    amd64        audio plugin host
ii  carla-lv2                                       2:1.9.7+git20170520v5.1                    amd64        audio plugin host (LV2 plugin)
ii  carla-vst                                       2:1.9.7+git20170520v5.1                    amd64        audio plugin host (VST plugin)
```

**Comment by rcspam** [comment] 2017-07-02 10:14
Ok falkTX, thanks, the reinstall had fix the problem, strange...
The only plugins which doen't work anymore is "addictive drums"  now.
```
Loading "Addictive Drums.dll"... done
Testing VST compatibility... WARNING: Sample rate requested but not yet set
WARNING: Buffer size requested but not yet set
Initialising Windows subsystem... done
cannot create dummy timer window
DSSIVSTPluginInstance::DSSIVSTPluginInstance(Addictive*Drums.dll) construction complete
DSSIVSTPlugin::configure(DSSI:SUPPORTS_CUSTOMDATA,)
DSSIVSTPluginInstance::configure(DSSI:SUPPORTS_CUSTOMDATA,)
client sized shm to 128
sized shm to 128, 0 inputs and 16 outputs
dssi-vst-server[1]: reset
Carla assertion failure: "fUniqueId == uniqueId" in file CarlaPluginBridge.cpp, line 1978, v1 6681, v2 6680
Carla Bridge Ready!
client sized shm to 16384
Carla assertion failure: "nframes == pData->bufferSize" in file CarlaEngineJack.cpp, line 1553
Carla assertion failure: "frames > 0" in file CarlaPluginBridge.cpp, line 1631
Carla assertion failure: "nframes == pData->bufferSize" in file CarlaEngineJack.cpp, line 1553
Carla assertion failure: "nframes == pData->bufferSize" in file CarlaEngineJack.cpp, line 1553Carla assertion failure: "frames > 0" in file CarlaPluginBridge.cpp, line 1631

Carla assertion failure: "nframes == pData->bufferSize" in file CarlaEngineJack.cpp, line 1553
Carla assertion failure: "frames > 0" in file CarlaPluginBridge.cpp, line 1631
Carla assertion failure: "frames > 0" in file CarlaPluginBridge.cpp, line 1631
Carla assertion failure: "nframes == pData->bufferSize" in file CarlaEngineJack.cpp, line 1553
..... REPEAT same lines and fill the memory, it crash pulseaudio !
```

**Comment by rcspam** [comment] 2017-07-02 10:16
Precision: AddictiveDrum works from vst-host without any problem... This problem happened only in carla !

**Comment by rcspam** [comment] 2017-07-02 10:49
I think my problem about win32 plugins come from VST2 engine, if i run it in DSSI, it runs right (except AdictiveDrums), but not in VST2... All my carxp files was save with VST2 mode....
In VST2 mode carla tell me:
```
No compatible plug-in format exists for this plug-in
```
Hope you can know me to retrieve with this infos...
I have a lot of carxp files i have to use :(
Thanks

**Comment by rcspam** [comment] 2017-07-02 11:09
a simple:
```
$ carla win32 vst2 Addictive\ Drums.dll
```
works very well, why not in carla...

Pic of my carla engine config:
![settings_001](https://user-images.githubusercontent.com/10021906/27769324-8dcc9bea-5f27-11e7-8de9-a74b39d33d3e.png)

**Comment by falkTX** [comment] 2017-07-02 13:33
I don't know what's going on.. something too strange, sorry can't help here.

**Comment by rcspam** [comment] 2017-07-02 16:18
Thanks, i let you know if i found the problem

**Closed** 2017-07-13 13:06 UTC
