### ISSUE TITLE
Installation error on Archlinux during carla-git installation

### ISSUE THREAD

**Issue by sshnip** [falkTX/Carla#1127] opened 2020-05-10 23:29 UTC
Hello, I was curious about reason of such issue?
I'm using Archlinux and install carla-git from the AUR. I realize that this issue could be absolutely with not regards to the carla codebase. Anyway, would really appreciate any help on resolving that
```
# Install vst plugin
install -d /home/crusty/.cache/yay/carla-git/pkg/carla-git//usr/lib/vst/carla.vst
install -m 644 \
        bin/CarlaRack*.* \
        bin/CarlaPatchbay*.* \
        /home/crusty/.cache/yay/carla-git/pkg/carla-git//usr/lib/vst/carla.vst
install: cannot stat 'bin/CarlaRack*.*': No such file or directory
install: cannot stat 'bin/CarlaPatchbay*.*': No such file or directory
make: *** [Makefile:550: install_main] Error 1
==> ERROR: A failure occurred in package().
    Aborting...
```

**Comment by mxmilkb** [comment] 2020-05-11 12:01
As @SpotlightKid reports in the AUR comments that they cannot reproduce, I would suggest you try a chroot build, which is the best way to see whether the issue is with the src/PKGBUILD or with the build environment where it is failing. https://wiki.archlinux.org/index.php/DeveloperWiki:Building_in_a_clean_chroot

**Comment by sshnip** [comment] 2020-05-11 12:13
Thanks for the really quick and helpful response! I'm new to archlinux tho.
I'll try that asap and report if anything goes wrong.

**Comment by mxmilkb** [comment] 2020-05-11 12:15
Welcome to the community, check out #archlinux-proaudio on freenode if you're IRC inclined, and the [LinuxMusicians](https://linuxmusicians.com) web forum if you haven't before :)

**Comment by SpotlightKid** [comment] 2020-05-11 14:28
The immediate cause of the error is that the install command in the make file can't find `bin/CarlaRack*.*` and `bin/CarlaPatchbay*.*`.

Apparently `bin/CarlaRackFX.so`,  `bin/CarlaRack.so`,  `bin/CarlaPatchbay16.so`, `bin/CarlaPatchbay32.so`, `bin/CarlaPatchbay64.so`, `bin/CarlaPatchbayFX.so`,  and `bin/CarlaPatchbay.so` do not get built in your build environment.

In the [build log you posted](https://pastebin.com/KdR6sfeH) I don't see any lines like "Linking CarlaRack.so" etc., which should be there.

**Comment by sshnip** [comment] 2020-05-11 17:14
`make features` looks extremely strange :)
```
---> Main features 
Front-End:     YES
LV2 plugin:    YES
VST plugin:    YES
Link support:  YES
OSC support:   YES
Binary detect: NO  [Missing libmagic/file]

---> Engine drivers 
JACK:        YES
ALSA:        YES
PulseAudio:  NO  [Missing PulseAudio]
CoreAudio:   NO  [MacOS only]
ASIO:        NO  [Windows only]
DirectSound: NO  [Windows only]
WASAPI:      NO  [Windows only]

---> Plugin formats: 
Internal: YES
LADSPA:   YES
DSSI:     YES
LV2:      YES
VST:      YES (without UI) [Missing X11]

---> LV2 UI toolkit support: 
External: YES (direct)
Gtk2:     NO  [Gtk2 missing]
Gtk3:     NO  [Gtk3 missing]
Qt4:      NO  [Qt4 missing]
Qt5:      YES (bridge)
X11:      NO  [X11 missing]
Cocoa:    NO  [MacOS only]
Windows:  NO  [Windows only]

---> File formats: 
Basic: NO [libsndfile missing]
Extra: NO [FFmpeg missing or too new]
SF2/3: YES
SFZ:   YES

---> Internal plugins: 
Basic Plugins:    YES
Carla-Patchbay:   YES
Carla-Rack:       YES
External Plugins: NO
```
Info regarding packages libs installed atm
```
$ pacman -Q | grep pulse
libcanberra-pulse 0.30+2+gc0620e4-3
libpulse 13.0-3
pulseaudio 13.0-3
pulseaudio-jack 13.0-3
pulseaudio-qt 1.2-1

$ pacman -Q | grep x11
lib32-libx11 1.6.9-1
libx11 1.6.9-6
libxkbcommon-x11 0.10.0-1
qt5-x11extras 5.14.2-1
xorg-x11perf 1.6.1-1

$ pacman -Q | grep libmagic
libmagick6 6.9.11.10-1

$ pacman -Q | grep ffmpeg
ffmpeg 1:4.2.2-6
ffmpegthumbs 20.04.0-1
opera-ffmpeg-codecs 81.0.4044.129-1

$ pacman -Q | grep libsndfile
libsndfile 1.0.28-3
```
To reduce unused info, same for gtk2/3. Seems like for some reason these libraries are not detected during compilation

**Comment by SpotlightKid** [comment] 2020-05-11 18:22
Are you maybe missing `pkgconf`? It should be installed as part of `base-devel`, which is assumed to be a dependency of every AUR package.

**Comment by falkTX** [comment] 2020-05-11 20:37
The lack of X11, however that is triggered, causes the install to fail.
But something is not right here, as it shows pretty stuff you have installed as missing.
Once that is resolved (dont use arch myself, so no ideas..) then you will need to rebuild carla

**Comment by falkTX** [comment] 2020-05-18 01:49
Going to close this since not having a working pkg-config is kinda deal-breaking. not just to build carla, but to build anything.
So Carla rightly assumes there is one in the system when building it.

**Closed by falkTX** 2020-05-18 01:49 UTC

**Comment by sshnip** [comment] 2020-05-19 07:48
@falkTX Sorry for the late reply. So the final issue was some kind of system inconsistency. Actually, everything worked/compiled/updated very well with no problems but it appeared that something was wrong and it affected carla compilation from the source. After all packages reinstallation `# pacman -Qqn | pacman -S -` everything worked like a charm
