### ISSUE TITLE
modules in the patchbay reset positions when loading project file.

### ISSUE THREAD

**Issue by Skrappjaw** [falkTX/Carla#1552] opened 2021-12-19 15:34 UTC
Every time I load up Carla the positions are reset or random. Some in the top left corner or bottom left. Also happens when selecting/moving multiple modules at the same time.
![Carla-Pathcbay](https://user-images.githubusercontent.com/21233073/146680468-ba3f72d9-350e-4764-8d5d-62c0abe4007a.png)

Also, this is how i startup jack/pulse and config my audio bridges....

>#!/bin/bash
killall -9 carla
killall -9 jackdbus
killall -9 pulseaudio
sleep 5
jack_control start & 
sleep 1
pulseaudio --start
cadence &
sleep 2
pacmd unload-module module-jack-sink
pacmd unload-module module-jack-source
sleep 2
#pulseaudio bridges | in / out
pacmd load-module module-jack-source channels=2 source_name=voip-in client_name=voip-in connect=false
pacmd load-module module-jack-sink channels=2 sink_name=voip-out client_name=voip-out connect=false
pacmd load-module module-jack-sink channels=2 sink_name=games-out client_name=games-out connect=false
pacmd load-module module-jack-source channels=2 source_name=media-in client_name=media-in connect=false
pacmd load-module module-jack-sink channels=2 sink_name=media-out client_name=media-out connect=false
sleep 2
#a2jmidid -e &
sleep 5
#carla &
carla ~/carla.setup.carxp &
sleep 3
wall "Audio systems up and running"
sleep 1
exit 0

I've tried starting carla with and without the project file being opened via the script. 

OS- Garuda Linux on Zen Kernel.

**Comment by mxmilkiib** [comment] 2021-12-19 15:37
Exactly what versions of JACK and Carla are you using? I think at least JACK might be out of date.

**Comment by Skrappjaw** [comment] 2021-12-19 16:19
Carla - 2.4.1
jack2 - 1.9.19

**Comment by All3xJ** [comment] 2021-12-30 17:53
I have the same issue with Carla 0.9. The patch https://github.com/falkTX/Carla/pull/1554 (so https://github.com/All3xJ/Catia/tree/patch-1 under Catia) does not fix the bug for me.

**Comment by All3xJ** [comment] 2022-01-02 14:27
I know that I am talking about Catia, but I find it weird that two very similar softwares have the same bug at the same time (@Skrappjaw reported the bug 14 days ago, which was more or less the same period I encoutered the bug in Catia). So I think they are in some way related. @Skrappjaw uses Garuda, I use ArchLinux, so I think that since these are bleeding edge distros, it must be an update of some package that caused the issue. I also tried downgrading pipewire, but it does not fix. I don't really know what could have caused the issue. Any suggestion about any package that may have caused this issue? I can try to downgrade it and see if it fix.

**Comment by udf** [comment] 2022-01-02 18:27
I'm facing the same issue on Arch Linux, I think it started from the python 3.10 upgrade.

I downgraded the following packages and it seemed to fix the issue:

python 3.10.1-2 ->3.9.9-1
python-pyqt5 5.15.6-6 -> 5.15.6-2
python-pyqt5-sip 12.9.0-3 ->12.9.0-1

None of the package versions changed, just the release number (aside from python of course). 

---

I also tried building the current [python-pyqt5](https://github.com/archlinux/svntogit-packages/blob/3c3dbe4e9194b91714e2f3335a1fa5520a3a91ef/trunk/PKGBUILD) and [python-pyqt5-sip](https://github.com/archlinux/svntogit-packages/blob/4b52057b6a61bb8e9d975f7fec5f40d4d7833019/trunk/PKGBUILD) packages for python 3.9 since there were some minor revisions which might have caused the bug, but I can't reproduce the issue on python 3.9.

**Comment by All3xJ** [comment] 2022-01-02 20:30
> I'm facing the same issue on Arch Linux, I think it started from the python 3.10 upgrade.
> 
> I downgraded the following packages and it seemed to fix the issue
I confirm

**Comment by BlueMax** [comment] 2022-01-02 21:49
Maybe some more float/int Python bugs.

Below is a video showing some of the behavior i've noticed in Carla: 
- Loading a project results in some bad node positions. Usually (some time ago) only the default nodes (input/output) were misplaced. But oddly the 'spectr' node is bad now as well. I recently re-assigned its port and re-saved the project. Possible that re-assigning ports corrupts the node/project now. Just saving the project seems ok.
- Another issue is the 'Loopack' node. It jumps back to top/left when i move the 'Loopback monitor' node.
- Some nodes/cables are flickering when moved across the screen. They seem to quickly jump to top/left and back.
- Sometimes nodes are offscreen or bottom/right (instead of top/left).

Carla 2.4.1.r34.g036f208cc-1
Arch Linux 5.15.12
Python 3.10.1

https://user-images.githubusercontent.com/1403092/147890278-226be831-9115-4e4f-b42a-79f857ac58ea.mp4

**Comment by falkTX** [comment] 2022-01-02 22:09
could be partially pipewire's fault too, which has received many tweaks around this.

for now, because of the many issues seen when using pipewire, I am just ignoring them completely.
unless using jack1 or jack2, I expect such issues to still happen from time to time.
we should fix things for when using proper/real jack first, then figure out the pipewire stuff after.

**Comment by BlueMax** [comment] 2022-01-02 23:17
c9c0375bf428d62ac472630d5ba748abe1cebaa1 helps alot. All bugs i've mentioned above seem fixed but the 'Loopback' <> 'Loopback monitor' one. Probably a Pipewire bug. Now, instead of jumping to top/left it "follows" the other node (placed behind). They seem somehow "connected". Maybe they share the same ID or something.

**Comment by All3xJ** [comment] 2022-01-02 23:19
Thanks for answer!

> could be partially pipewire's fault too, which has received many tweaks around this.

which tweaks? if you talk about this: https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1945 the issue was not fixed after these. 


> for now, because of the many issues seen when using pipewire, I am just ignoring them completely. unless using jack1 or jack2, I expect such issues to still happen from time to time. we should fix things for when using proper/real jack first, then figure out the pipewire stuff after.

I have starting to have this issue only two weeks ago, and I downgraded pipewire to older versions (months ago), but the bug is still there.

**Comment by All3xJ** [comment] 2022-01-02 23:22
> [c9c0375](https://github.com/falkTX/Carla/commit/c9c0375bf428d62ac472630d5ba748abe1cebaa1) helps alot. All bugs i've mentioned above seem fixed but the 'Loopback' <> 'Loopback monitor' one. Probably a Pipewire bug. Now, instead of jumping to top/left it "follows" the other node (placed behind). They seem somehow "connected". Maybe they share the same ID or something.

does patchbay works well to? for example if you are recording your microphone into some apps and try to put the audio output of some music to input of the recording app?

**Comment by Skrappjaw** [comment] 2022-01-02 23:51
> could be partially pipewire's fault too, which has received many tweaks around this.
> 
> for now, because of the many issues seen when using pipewire, I am just ignoring them completely. unless using jack1 or jack2, I expect such issues to still happen from time to time. we should fix things for when using proper/real jack first, then figure out the pipewire stuff after.

I'm using jack2 on Garuda (arch) . I can confirm the issues post python update. Ill try the python downgrade to see if issues persist.

**Comment by udf** [comment] 2022-01-03 00:02
@Skrappjaw Can you try installing carla-git? c9c0375 seems to solve most of the issues for me too.

**Comment by Skrappjaw** [comment] 2022-01-03 00:16
> @Skrappjaw Can you try installing carla-git? [c9c0375](https://github.com/falkTX/Carla/commit/c9c0375bf428d62ac472630d5ba748abe1cebaa1) seems to solve most of the issues for me too.

Everytime I try Carla git from AUR it fails for some reason. I'll try as soon as I can. I'm moving this week and probably won't have my studio set back up for a couple weeks. Unfortunately. But, I do know that there was a manual intervention required with the way python updates work with arch. I had a heck of a time working it out but after that, these Carla issues began.

**Comment by BlueMax** [comment] 2022-01-03 13:12
> does patchbay works well to? for example if you are recording your microphone into some apps and try to put the audio output of some music to input of the recording app? It does not work for me

I don't have such a setup. All my connections (as in the video above) do work.

**Comment by All3xJ** [comment] 2022-01-06 12:47
@udf the python, python-pyqt5, and python-pyqt5-sip downgrades seem to have broken gnome-tweaks(it says "ModuleNotFoundError: No module named 'gi'"), and maybe other stuff I guess.
What's your current situation? You are still having the downgraded packages?

**Comment by udf** [comment] 2022-01-06 13:08
@All3xJ No I'm not using downgraded packages because as I said before, downgrading python breaks all other system python packages since they're for 3.10.

I'm using carla-git from the aur, c9c0375 fixes most of the issues but it's not in a release version yet.

**Comment by All3xJ** [comment] 2022-01-06 14:53
@udf does patchbay works well to? for example if you are recording your microphone into some apps and try to put the audio output of some music to input of the recording app? It does not work for me. And this is what I use Carla and Catia for, and I must keep downgraded the packages.

**Comment by All3xJ** [comment] 2022-01-11 13:53
Now on Carla the problem is gone. With Catia, the bug is still there and it's not usable.

**Comment by falkTX** [comment] 2022-01-21 20:16
Closing this since issue is fixed on latest git. Release will be made soon

**Closed by falkTX** 2022-01-21 20:16 UTC

**Comment by All3xJ** [comment] 2022-01-22 09:22
> Closing this since issue is fixed on latest git. Release will be made soon

Great news. Is it also fixed in Catia?

**Comment by falkTX** [comment] 2022-01-22 09:24
No, Catia will need a proper release after being split off from Cadence.
I havent even made the Carla release yet, and still have Ildaeil and WineASIO to handle too first.

So this is going to take a while.

**Comment by All3xJ** [comment] 2022-02-06 14:00
Update: now on Carla, in patchcanvas, I can't see the input and output devices.... I can only see these and they don't seem to be useful:
![image](https://user-images.githubusercontent.com/20903913/152684407-33b5e6e6-cd41-41d3-8c5e-13fa8946924f.png)

**Comment by mxmilkiib** [comment] 2022-02-06 15:20
That looks like the internal patchbay. There is a menu option to change the view between internal and external. Or change Carla to multi-client mode in the settings and every plugin becomes a JACK client, so you're dealing with just one audio graph. This is explained in the home page but it still catches many folk out, I think tabs is the solution https://github.com/falkTX/Carla/issues/564#issuecomment-361920082

**Comment by All3xJ** [comment] 2022-02-10 19:57
> That looks like the internal patchbay. There is a menu option to change the view between internal and external. Or change Carla to multi-client mode in the settings and every plugin becomes a JACK client, so you're dealing with just one audio graph. This is explained in the home page but it still catches many folk out, I think tabs are the solution (for the first part, as that itself doesn't indicate that multi-client mode exists) [#564 (comment)](https://github.com/falkTX/Carla/issues/564#issuecomment-361920082)

If I set to external, I can only see this:
![image](https://user-images.githubusercontent.com/20903913/153486671-53a8cdd6-0732-4566-9e1c-6a3b28c07b80.png)
so there must be something wrong.

**Comment by falkTX** [comment] 2022-02-10 20:47
that is patchbay engine mode, change it to multi-client.

**Comment by All3xJ** [comment] 2022-02-10 22:47
> that is patchbay engine mode, change it to multi-client.

I noticed that I had Audio driver set to "Pulseaudio". I have set it to "JACK" and then the mode set to "Multiple clients" and now it works again :)
