### ISSUE TITLE
incorrect MIDI behaviour for Calf instruments in Carla

### ISSUE THREAD

**Issue by moonshaadow** [falkTX/Carla#981] opened 2019-12-11 18:07 UTC
Hello there,

Using Calf instruments in Carla 2.0.0, incorrect MIDI channel behaviour. In Calf, Channel set on 0 receives OMNI (that is correct), but set on 1 receives channel 2, set on 2 receives channel 3 ....

Can't reproduce with  Calfplugin in calfjackhost. Can't reproduce with other plugins in Carla.

**Comment by falkTX** [comment] 2019-12-11 18:25
I do not follow. set on 0 and set on 1 exactly where, what does it refer to?

**Comment by moonshaadow** [comment] 2019-12-11 19:13
_( Sorry, my self-translation is so bad ! )_ 
I mean setting the 'channel' button on the calf GUI. If I set it to "1", the plugin receives only incoming midi from channel 2.

**Comment by moonshaadow** [comment] 2019-12-19 15:01
This button in "Calf Organ" works fine in calfjackhost, but not in carla :
![Capture d’écran_2019-12-19_15-55-21](https://user-images.githubusercontent.com/29754932/71183330-190e2a00-2278-11ea-94cd-c81e498a40ad.png)

Setting it to value '0' makes plugin receiving MiDI from all channels, that is ok, setiing it to value '1' makes plugin receiving MiDI from channel 2, that is not expected.

**Comment by falkTX** [comment] 2019-12-19 16:45
Please check if the behaviour is the same in other lv2 hosts. jalv likely the simplest one.
This way we verify if the issue is in carla, or calf's lv2 implementation

**Comment by moonshaadow** [comment] 2019-12-20 10:51
OK, you're right. Same issue in Ardour. _(for some reason I can't build jalv, but seems to be a nice tool)._
So this should not be a carla issue.
I report the issue to calf developers. 
Thank you!

**Comment by falkTX** [comment] 2019-12-20 15:46
alright, I am closing this issue then. thanks.

**Closed by falkTX** 2019-12-20 15:46 UTC
