### ISSUE TITLE
2.2.0 Gives cx_Freeze - DLL Load Failed on Windows

### ISSUE THREAD

**Issue by casper** [falkTX/Carla#1273] opened 2020-10-14 18:40 UTC
Using 2.2.0 32-bit (also tried the noSSE version) on Windows Vista 32-bit SP2 I get Python error in main script when running `Carla.exe`.

![image](https://user-images.githubusercontent.com/25386/96030932-537b3000-0e65-11eb-836c-b98056475bb2.png)

Is there some other components I need to install, or does it not work on Vista?

**Comment by falkTX** [comment] 2020-10-14 18:42
hmm I am not sure if Vista is still supported. Got another PC you can try the same build on?

**Comment by casper** [comment] 2020-10-14 18:52
Not so easily. I have a remote Windows 8 64-bit VPS. Want me to test it there? At the moment I'm going though old versions to try and figure out if any of them work on this Vista machine. 2.1.1 has the same issue.

**Comment by casper** [comment] 2020-10-14 19:01
2.0.0 works. So the problem is somewhere between 2.0.0 and 2.1.1.

**Comment by falkTX** [comment] 2020-10-14 21:07
that is not going to solve anything though. 2.0 used some very old stuff for the GUI, while on 2.1 onwards it was updated.

Might be due to using Vista, not sure.

**Comment by casper** [comment] 2020-10-14 22:42
Yeah. 2.1 doesn't work either. 2.0.0 uses Qt 5.5.1, while I saw a comment about Qt 5.15 among the latest releases. It could be Qt 5.15 is not compatible with < Win 7(?).

I also realized my VPS is not Win 8, but Windows Server 2012 R2 (basically server version of Win 8), so not sure how valid testing there is. I did it anyway. 2.0.0 works, 2.2.0 both 32 and 64 bits fail, both with different error messages, and not the same as on Vista.

![image](https://user-images.githubusercontent.com/25386/96053149-a9f96600-0e87-11eb-81a2-c7cc3d3f5344.png)

![image](https://user-images.githubusercontent.com/25386/96051776-e8415600-0e84-11eb-9c9b-628ea8d536de.png)

**Comment by kapseli** [comment] 2021-01-11 19:31
I'm seeing the same issue with Win10 (20H2, 19042.685), both 32bit and 64bit.

**Comment by falkTX** [comment] 2021-01-11 19:39
I was able to reproduce the issue in the 32bit build, so going to take a look at this for the 2.3 release.

**Comment by kapseli** [comment] 2021-01-11 19:44
2.1 seems to start okay on my system.
And I noticed minor difference to the original error, last traceback line is: File ".\lib\carla_host.py", line **43**, in <module>

**Comment by falkTX** [comment] 2021-04-03 09:46
This is fixed in 2.3 release, currently in RC but to be out as stable soon.

**Closed by falkTX** 2021-04-03 09:46 UTC
