### ISSUE TITLE
Multi instance Carla and Claudia persistent connections

### ISSUE THREAD

**Issue by christianwn** [falkTX/Carla#787] opened 2018-11-06 20:52 UTC
Hi this is a suggestion and also a question if anyone has a resolution.

When you open a jack enabled program like Carla it's connection name is shown as Carla in Claudia. The Second instance is shown as Caral-02 etc...
But for persistent connections you need to be able to name those program connections. F eks in Mixbus you can rename the insert points and channel strip names etc. This change you will instantly see in Claudia and when you save in Claudia these connections are remembered.
The point here is that, as it is now, you must start each instance of Carla in the right order to achieve this. Because if you start any instance of Carla in the wrong order the connections will go to wrong places.
I think the right solution would be to have an option in Carla to name it's connections and those names be saved with the rest of the settings, when you save your rack. Put a text box among the gui buttons or something to name the ports or Rack instance you have and have this reflected in the port names.

I see this as a very important feature for proper functionality that would benefit all, I can not code this my self, so I would donate 20€ for this cause, if it helps.

Thank you for your effort :-)
Christian W. Nyman

![mixbus_example](https://user-images.githubusercontent.com/44818911/48092840-b8539780-e205-11e8-849e-6d51e1dc6b16.png)

![exampel](https://user-images.githubusercontent.com/44818911/48092645-264b8f00-e205-11e8-95d2-3df1dacc33a4.jpg)

**Comment by falkTX** [comment] 2018-11-21 07:49
I am not sure if I understand this.
By design, running Carla inside Claudia (or just ladish), it will take whatever name you give it and use it as the jack client name.

The screenshots you posted are confusing, since you seem to be running carla, but outside of claudia...

In any case, when starting Carla manually, you can export a variable name and carla will just its default client name.
```
env CARLA_CLIENT_NAME="Carla-first" carla-patchbay
env CARLA_CLIENT_NAME="Carla-more" carla-rack
```

**Comment by falkTX** [comment] 2020-06-29 16:25
I am considering this issue completely fixed with the latest changes in git/develop.
A "--cnprefix" CLI argument exists now that allows us to set a custom client name prefix on all jack clients that carla creates.
Carla will automatically add the prefix when loading a project without it (though you need to have saved that first with the git/develop version first).
Carla will also be able to load a project made with a custom client name prefix, but running on an instance without it.
Lastly, when running a 2nd instance of carla, it will give itself a unique client name prefix in order to avoid conflicts.

This will be part of 2.2-RC1 that I am preparing for release in a few weeks.

**Closed by falkTX** 2020-06-29 16:25 UTC
Labels: discussion
