### ISSUE TITLE
Native Helm GUI (lv2 and vst) are not displayed

### ISSUE THREAD

**Issue by ghost** [falkTX/Carla#452] opened 2017-01-10 20:25 UTC
I'm using Debian "Jessie" (AntiX) 32-bit, and noticed that Helm's native GUI provides only a black window. 

brian

**Comment by SpotlightKid** [comment] 2017-01-21 14:55
Can't reproduce this on 64-bit arch (using helm-git AUR package). GUI shows fine here.

Does the GUI show using helm's standalone version?

**Comment by amsynthdotcom** [comment] 2017-01-23 22:00
The GUI is fine in standalone version, as well as the (LV2?) version using jalv.gtk.

brian

**Comment by falkTX** [comment] 2017-11-28 21:19
I was never able to reproduce this issue...
Does it still happen?

**Comment by trebmuh** [comment] 2018-09-22 19:59
FWIW, I've just tried with 2.0-RC1 on a Debian Stretch, and the Helm GUI appears as expected. Both with LV2 and VST2 version.

**Comment by trebmuh** [comment] 2018-09-22 20:02
PS: @falkTX it looks like the [ghost user](https://github.com/ghost) is a kind of "account-deleted" user in the github realm.

**Comment by falkTX** [comment] 2018-09-22 23:40
ah, thanks for noticing.
I guess the user is no longer interested on the issue. closing

**Closed by falkTX** 2018-09-22 23:40 UTC
Labels: bug, needs recheck
