### ISSUE TITLE
Carla 2 beta 7 crashes when loading VST Plugins (Windows 32 Bit No SSE) 

### ISSUE THREAD

**Issue by E-Gwen** [falkTX/Carla#673] opened 2018-07-25 13:32 UTC
Hi,

Unfortunately, Carla 2 beta 7 will systematically crash when you try to load a VST plugin using Windows XP 32 bit SP3.

I didn't have time to report it, but it was already the case with the beta 6.

There is no particular message, except the Windows proposal for a bug report.

When you click for the details, it incriminates "libcarla_standalone2.dll"

At your service for more information.

**Comment by E-Gwen** [comment] 2018-08-17 11:05
All vst plugins crash, many dozen of them.

I use only VST DLL plugins that run with Windows XP, of course.
When a VST does not work, I notice the programmer for the issue.
For example, i can't use Dexed 0.9.4, despite 0.9.3 was working fine.

Each VST DLL plugin works fine with Ardour 5.10, or 6.0 alpha, with LMMS 1.2RC6 too, and OcenAudio 3.3.10.

Everything was running fine with Carla 2.0 beta 5, which were not build with no SSE feature.

In that case, it is a serious regression.

Hope you will find how to fix it.

Best regards.

**Comment by falkTX** [comment] 2018-08-18 18:04
It is a serious regression yes, I did not know there was such an issue until now.
Likely something to do with the move away from Juce, to handle VST directly.
I will attention to this bug for the next beta, sorry for the inconvenience, I don't usually test on Windows.

**Comment by E-Gwen** [comment] 2018-08-20 16:35
Thank you for your attention;
And don't be sorry, you are making an amazing tool ! It's a pleasure testing for you.
Can't wait trying the beta 8 version.

See you.

**Comment by falkTX** [comment] 2018-08-21 16:37
I am looking at this bug, need to make sure I understand what is going on.
Please try the beta6-nosse build and let me know if it works for you.
Here https://github.com/falkTX/Carla/releases/download/1.9.8/Carla_2.0-beta6-win32-nosse.zip

**Comment by falkTX** [comment] 2018-08-22 11:01
Alright, new binary!
https://github.com/falkTX/Carla/releases/download/v1.9.9/Carla_2.0-beta7.2-win32-nosse.zip

I ran it on a laptop with windows 10, seems quite fine.
There are some new things on this binary, since the code has changed a bit now.
I am more interested to know if it loads without crashing or not...

**Comment by E-Gwen** [comment] 2018-08-23 10:29
Ok, there is no more crash.

But there is no more link between patchbay and Jack (1.9.11) neither.
When you connect plugin in patchbay, no sound comes. You have to enter Jack to make connections and to hear the sound.

Some settings are not available for VST Digits plugin, for example, despite OB-XD or Tunefish settings are.

When you have two VST plugins loaded and exit Carla, it will crash.

I'll make a longer test.

**Comment by falkTX** [comment] 2018-08-24 10:07
I did some changes regarding RtAudio and auto-connecting to system ports, WIP.

I just realized, due to #696, that the compiler I am using for windows is buggy.
Please don't bother testing for now until I update that, the binaries we have now can have random crashes :(

**Comment by falkTX** [comment] 2018-09-05 19:08
Ok, new binary is here!
https://github.com/falkTX/Carla/releases/download/v1.9.9/Carla_2.0-beta7.3-win32-nosse.zip

I updated my compiler, should not have some of the same issues as before.
I'm closing this bug since the issue it mentions is actually fixed.
Please test that binary, and report back any issues.

**Closed by falkTX** 2018-09-05 19:08 UTC
Labels: bug, needs recheck
