### ISSUE TITLE
Refresh plugins crashes with TypeError

### ISSUE THREAD

**Issue by BlueMax** [falkTX/Carla#1590] opened 2022-02-20 16:53 UTC
When pressing the 'Refresh' button this error shows up in Carla log and nothing happens:
```
Traceback (most recent call last):
  File "/usr/share/carla/carla_database.py", line 1692, in slot_refreshPlugins
    if PluginRefreshW(self, self.host, self.fUseSystemIcons, self.hasLoadedLv2Plugins).exec_():
  File "/usr/share/carla/carla_database.py", line 1230, in __init__
    self.fThread.pluginLook.connect(self.slot_handlePluginLook)
TypeError: decorated slot has no signature compatible with SearchPluginsThread.pluginLook[float, str]
```
Arch Linux 5.16.10
Carla 2.4.2.r0.g7b8eeef34-1

**Comment by windowsrefund** [comment] 2022-02-20 18:37
Same thing here on Ubuntu 21.10
```
carla 5:2.4.2
carla-bridge-win32:i386 5:2.4.2+git20220219
carla-bridge-win64 5:2.4.2+git20220219
carla-bridge-wine32 5:2.4.2+git20220219
carla-bridge-wine64 5:2.4.2+git20220219
carla-data 5:2.4.2
carla-lv2 5:2.4.2+git20220219
carla-vst 5:2.4.2+git20220219```

**Comment by kamelie1706** [comment] 2022-02-21 05:31
Confirmed it crashes in arch Linux, seems a python/ui bug. Is there a way to run plug-in refresh from the command line?

**Comment by falkTX** [comment] 2022-02-21 09:51
Fixed in 7e16efba89c180f170c6fe22c773742cfbb89f17
I am not using python 3.10, so didnt notice the issue until too late :(

I asked the archlinux maintainer to update it.

**Closed by falkTX** 2022-02-21 09:51 UTC

**Comment by kamelie1706** [comment] 2022-02-21 11:57
Thx and confirm working in Arch!

**Comment by windowsrefund** [comment] 2022-02-21 15:55
The kxstudio packages don't appear to have been updated?

**Comment by eldorel** [comment] 2022-03-24 15:55
> The kxstudio packages don't appear to have been updated?

I just ran into this bug today with the 2.4.2-win64 version downloaded directly from kxstudio.
It looks like the fix for this hasn't been pushed into a released build yet.

**Comment by elbvdk** [comment] 2022-05-07 00:36
Seems to also be an issue still on Ubuntu 22.04 as well.

**Comment by alpianon** [comment] 2022-12-28 10:58
> Seems to also be an issue still on Ubuntu 22.04 as well.

confirm

**Comment by illtellyoulater** [comment] 2023-11-06 08:14
So basically all it takes to fix it, is modifying line 1361 of `/usr/share/carla/carla_database.py` from

`@pyqtSlot(int, str)`

to

`@pyqtSlot(float, str)`

I hope it gets pushed soon though.

**Comment by falkTX** [comment] 2023-11-06 09:08
it wont, everyone moved on to newer distros already. I hope we get to see 2.5.7 on 24.04 at least

**Comment by illtellyoulater** [comment] 2023-11-07 07:52
it works for me by changing that line

**Comment by Archytas79** [comment] 2025-12-06 05:09
necroing this issue to say that that line change worked for me on mint 21.3 kernel 6.15
