### ISSUE TITLE
Assertion failure as VST plugin on Ardour

### ISSUE THREAD

**Issue by enorrmann** [falkTX/Carla#1229] opened 2020-08-02 13:39 UTC
Running vst on ardour 6. 
As I start rolling (play) from ardour, carla crashes (and also Ardour) with message:
Carla assertion failure: "timeInfo.bbt.bar > 0" in file CarlaPluginVST2.cpp, line 1188, value 0

**Comment by falkTX** [comment] 2020-09-06 10:31
This is a duplicate of #1236 lets keep discussion there.

**Closed by falkTX** 2020-09-06 10:31 UTC
