### ISSUE TITLE
Harrison Mixbus LV2 plugis don't show their GUi

### ISSUE THREAD

**Issue by codecollider** [falkTX/Carla#793] opened 2018-11-13 23:44 UTC
In the latest CARLA version the Mixbus plugins don't show their GUI and a buzz occurs when trying to open the GUI. 

Carla 2.0 RC2

**Comment by falkTX** [comment] 2018-11-22 14:00
I cannot reproduce this issue.
If it possible for you to update the mixbus plugins? if not, try to see which exact version of them you have so I can ask the developer for the same build.

**Comment by codecollider** [comment] 2019-01-16 15:40
Problem still occurs with:

Using Carla version 1.9.13 (2.0-RC3)
  Python version: 3.5.3
  Qt version:     5.7.1
  PyQt version:   5.7
  Binary dir:     /usr/lib/carla
  Resources dir:  /usr/share/carla/resources

**Comment by falkTX** [comment] 2019-02-26 07:33
This is a tricky one, can no longer reproduce reliably but happens randomly :(
Will leave it for v2.1

**Comment by codecollider** [comment] 2019-03-30 15:51
ok, for me it's not working at all :)

**Comment by falkTX** [comment] 2020-09-24 03:47
This was fixed in 2.2, x11 child window not always valid, issue is actually duplicate of a few others ones.

**Closed by falkTX** 2020-09-24 03:47 UTC
Labels: bug
