### ISSUE TITLE
Carla bridge lv2-cocoa does not raise the window

### ISSUE THREAD

**Issue by jpcima** [falkTX/Carla#954] opened 2019-11-11 17:05 UTC
Hi, when a LV2 plugin opens a bridged UI on OS X, the window does not pop up in the foreground.
It starts positioned behind the Carla main window in the Z-order.

When it's a VST of the same plugin, the window shows in the foreground as usual.

Carla 2.0.0 on Mac Sierra

**Comment by falkTX** [comment] 2020-03-30 17:50
This is because the lv2 UIs are preferred to run in a bridge, as external process.
In macOS, afaik, it is not possible for one process to control the windows of another one (there are only old carbon-based hacks).

One thing that could work is to trigger focus of the new window when it becomes visible.
Will try that.

**Comment by falkTX** [comment] 2020-03-31 00:39
I committed and pushed without testing, but now that I got release out, I can confirm it works! :D

**Closed by falkTX** 2020-03-31 00:39 UTC
Labels: bug
