### ISSUE TITLE
Error while installing on Ubuntu studio

### ISSUE THREAD

**Issue by emixcopec** [falkTX/Carla#1241] opened 2020-08-24 13:26 UTC
Hi, i was installing on the directory with $make then $make install but it does nothing apparently, then i installed the dependences reccomended on the install.md and it give me this:

 
-# Adjust LIBDIR and DATADIR value in python code
sed -i -e 's?X_LIBDIR_X = None?X_LIBDIR_X = "/usr/local/lib"?' \
	/usr/local/share/carla/carla_shared.py
sed -i -e 's?X_DATADIR_X = None?X_DATADIR_X = "/usr/local/share"?' \
	/usr/local/share/carla/carla_shared.py
-# Install resources (gui)
install -m 755 \
	bin/resources/carla-plugin \
	bin/resources/carla-plugin-patchbay \
	bin/resources/*-ui \
	/usr/local/share/carla/resources
install: no se puede efectuar `stat' sobre 'bin/resources/carla-plugin': No existe el archivo o el directorio
install: no se puede efectuar `stat' sobre 'bin/resources/carla-plugin-patchbay': No existe el archivo o el directorio
install: no se puede efectuar `stat' sobre 'bin/resources/*-ui': No existe el archivo o el directorio
Makefile:417: fallo en las instrucciones para el objetivo 'install_main'
make: *** [install_main] Error 1

It means No such file or directory... i dont know what is the problem but my dependences are this:

---> Main features 
Front-End:     YES
LV2 plugin:    YES
VST2 plugin:   YES
Link support:  YES
OSC support:   YES
Binary detect: YES

---> Engine drivers 
JACK:        YES
ALSA:        YES
PulseAudio:  YES
CoreAudio:   NO  [MacOS only]
ASIO:        NO  [Windows only]
DirectSound: NO  [Windows only]
WASAPI:      NO  [Windows only]

---> Plugin formats: 
Internal: YES
LADSPA:   YES
DSSI:     YES
LV2:      YES
VST2:     YES (with UI)
VST3:     YES (with UI, using JUCE)
AU:       NO  [MacOS only]

---> LV2 UI toolkit support: 
External: YES (direct)
Gtk2:     YES (bridge)
Gtk3:     YES (bridge)
Qt4:      YES (bridge)
Qt5:      YES (bridge)
X11:      YES (direct+bridge)
Cocoa:    NO  [MacOS only]
Windows:  NO  [Windows only]

---> File formats: 
Basic: NO [libsndfile missing]
Extra: NO [FFmpeg missing or too new]
SF2/3: NO [FluidSynth missing or too old]
SFZ:   YES

---> Internal plugins: 
Basic Plugins:    YES
Carla-Patchbay:   YES
Carla-Rack:       YES
External Plugins: NO

**Comment by falkTX** [comment] 2020-08-24 23:18
did you install the additional libraries for the extra features after building?

what version of ubuntu is this?

**Comment by emixcopec** [comment] 2020-08-25 14:58
> did you install the additional libraries for the extra features after building?
>
> what version of ubuntu is this?

Yes, I have installed the additional dependencies using the command given in the install.md, but the libsndfile still missing even if it is installed maybe need to change the route but i don't know how.

My version is Ubuntu studio 16.04, i have seen a video of unfa where he plays a live set with carla and seq24 and i want to do the same... 

I also think that I could try adding a repository that allows me to install it via apt.

Thanks you for the help, i will be checking the files to see if I can change the path to libsndfile.

**Comment by falkTX** [comment] 2020-08-25 15:21
If you installed new libraries after building Carla, it will make the installation fail.
On this case simply rebuild carla again, and it should install fine at the end.

**Comment by emixcopec** [comment] 2020-08-25 15:29
yyeeesss i rebuilded and it works :33333 thx you veery very much

**Comment by emixcopec** [comment] 2020-08-25 15:30
sorry for the trouble

**Comment by falkTX** [comment] 2020-08-25 17:02
no worries, glad it is working. I am closing the ticket since the issue is "fixed"

**Closed by falkTX** 2020-08-25 17:02 UTC
