### ISSUE TITLE
mmap failed: Resource temporarely unavailable (win32/64 bridge)

### ISSUE THREAD

**Issue by Member1221** [falkTX/Carla#592] opened 2018-03-14 18:17 UTC
Whenever i try to use a win32/win64 bridge plugin, an error box appears stating "Failed to load plugin"

When looking in the log:
```
carla_shm_map() - mmap failed: Resursen midlertidig utilgængelig
Failed to initialize Non-RT client control
```

Resoursen midlertidig utilgængelig = Resource temporarely unavailable

I'm using wine 3.3

**Comment by falkTX** [comment] 2018-03-14 19:29
hmm is your system out of memory? too much stuff open?

what distro are you using? with what kernel?

**Comment by Member1221** [comment] 2018-03-14 20:03
Using Elementary OS, I have 9 GB memory free.

Kernel 4.13.0 Generic
User is not in audio group.

**Comment by fraunos** [comment] 2019-02-19 21:39
I just got the same problem... Installed wine-staging for a while, but reinstalling carla-git didn't help, so I'm not sure if this is the cause.

**Comment by falkTX** [comment] 2019-02-20 07:51
Does the same happen if you just load native linux plugins?

Go to settings, experimental, and enable the option near the end to run all plugins under bridge mode.
Then try to load a random lv2 plugin.
Does that work?

**Comment by fraunos** [comment] 2019-02-21 17:16
Hi, I followed the instructions provided by
https://github.com/raboof/realtimeconfigquickscan
and it is solved :)

**Comment by skuffe** [comment] 2019-03-22 20:48
@fraunos i have the same problem, can you provide some more details regarding the configs you changed to get this working?

**Comment by Member1221** [comment] 2019-03-22 21:05
@skuffe not often i meet a fellow dane here haha

Otherwise, yes i'd like to know as well; granted I haven't done any producing in a while.

**Comment by fraunos** [comment] 2019-03-24 07:58
These are the settings I got now - I'm not sure which I've changed to get it to work.
![obraz](https://user-images.githubusercontent.com/6673521/54876595-e7645180-4e12-11e9-879e-ccd5f2357ca8.png)

**Comment by skyfreezer** [comment] 2019-08-12 19:18
Was running into the same error. Was able to fix it by setting up my linux system for audio production. 
 - Add your current user to the audio group
(Ubuntu and related)
`sudo adduser "exampleuser" audio`
(Arch)
`gpasswd -a "exampleuser" audio`
 
 - Remove limits from your memory by editing your /etc/security/limits.conf or /etc/security/limits.d/audio.conf/.
`@audio - rtprio 90       # maximum realtime priority
 @audio - memlock unlimited  # maximum locked-in-memory address space (KB)`
 - Reboot your computer

**Comment by falkTX** [comment] 2020-08-17 17:13
I just installed elementary OS here in a VM.

The windows bridges work as-is with their latest release.
I did not have to do anything besides installing things and building carla.

![Screenshot_20200817_181221](https://user-images.githubusercontent.com/1334853/90424019-55b74d00-e0b5-11ea-81d5-1945b19fe6ef.png)

So I am closing this ticket.

**Closed by falkTX** 2020-08-17 17:13 UTC
