### ISSUE TITLE
Support for after touch in Carla?

### ISSUE THREAD

**Issue by polluxsynth** [falkTX/Carla#1386] opened 2021-03-25 22:16 UTC
I can't find any definitive information (save looking through the source code) on this, but I've read that Carla does not support after touch, which indeed seems to be the case (tested with a couple of VST3 plugins in Linux, comparing to hosting them in Ardour). Is there any special reason for this? I would expect that Carla would just pass MIDI data through from input to plugin, but at the same time I suspect there is something more to it or it would already have been implemented.

**Comment by falkTX** [comment] 2021-03-26 10:04
Is this about VST3 hosting?
VST3 have no real notion of MIDI, instead it uses its own way of defining notes. Since Carla simply uses JUCE for the VST3 hosting, either JUCE-VST3 code has this missing or there is something weird happening.

I know for sure that MIDI aftertouch is supported in Carla, though it depends on the plugins and formats in use.

**Comment by polluxsynth** [comment] 2021-03-26 11:46
Yes, in this case it was a VST3 plugin I was testing (Surge (https://surge-synthesizer.github.io/)). Other non-note controllers such as sustain pedal and pitch bend work, so it seems to be restricted to (channel) aftertouch (haven't tried poly aftertouch).

**Comment by falkTX** [comment] 2021-04-11 12:56
Might be fixed in 10b491b303d041cc8dcea55b162660fd3e979312
I didnt actually reproduce this though, just looked at the code and saw some missing things on juce side.
Testing would be very appreciated, thanks

**Comment by polluxsynth** [comment] 2021-04-11 20:41
Checked out the indicated revision, built and tested it, and yes, channel aftertouch works now! Tested with Surge and Dexed (both VST3). Thanks!

**Comment by falkTX** [comment] 2021-04-14 11:21
closing ticket then. will need to submit the juce changes upstream, have a ticket for myself somewhere else for this.

**Closed by falkTX** 2021-04-14 11:21 UTC
Labels: bug, needs recheck
