### ISSUE TITLE
Crash on Non Mixer channel strip rename

### ISSUE THREAD

**Issue by mxmilkb** [falkTX/Carla#1037] opened 2020-03-01 15:58 UTC
https://gist.github.com/mxmilkb/c6beeda184601910f3c72bfe6596ed57

**Comment by falkTX** [comment] 2020-03-01 16:19
no fancy canvas stuff enabled?

the crash goes deep into Qt stuff, likely unfixable right now.
but workarounds can be made.
are you able to reliably reproduce? if so, how?

**Comment by mxmilkb** [comment] 2020-03-01 17:33
I can't reproduce! Out of experimental features, only JACK apps was enabled. I did have Basic Eye Candy on and Anti-Aliasing, but I have tried again with off and on for each. Hmm.

**Comment by falkTX** [comment] 2020-03-30 17:05
Another ticket that is likely due to how carla was handling jack callback events.
I assume it is fixed in latest git, unless you can reproduce again.

**Closed by falkTX** 2020-03-30 17:05 UTC
