### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by CaptainBloodz** [falkTX/Carla#967] opened 2019-11-28 20:16 UTC
Installed versions:  9999*l(02:52:36 27/11/2019)(X gtk2 opengl osc rdf sf2 -alsa -ffmpeg -gtk -libav -pulseaudio -sndfile PYTHON_SINGLE_TARGET="python3_6 -python3_5 -python3_7" PYTHON_TARGETS="python3_6 -python3_5 -python3_7")
----------------------------------------------------------------------------------------------------------------------------------------
Compiling CarlaPluginVST2.cpp
CarlaPluginVST2.cpp: In member function 'virtual void CarlaBackend::CarlaPluginVST2::showCustomUI(bool)':
CarlaPluginVST2.cpp:553:25: error: 'struct CarlaBackend::CarlaPluginVST2::UI' has no member named 'isResized'
  553 |                     fUI.isResized = false;
      |                         ^~~~~~~~~
make[1]: *** [Makefile:80: ../../../build/backend/Release/CarlaPluginVST2.cpp.o] Error 1

**Comment by falkTX** [comment] 2019-11-28 20:39
Caused by partial revert, fixed in latest git

**Closed by falkTX** 2019-11-28 20:39 UTC
