### ISSUE TITLE
Exported LV2 plugins not loaded in Ardour

### ISSUE THREAD

**Issue by RockVice77** [falkTX/Carla#809] opened 2019-01-09 07:10 UTC
I just exported from  Carla a set of windows VST plugins with the "Export LV2..." command. All of them are properly workinng in the Carla Rack/Patchbay.  
When I try to re-open the LV2 exported plugins in Ardour I am able load just one plugin at a time. 

Here below an exemple of the output from the command line after the first loaded plugin
`lv2_descriptor(0) has URI 'file:///home/rocco/.lv2/Rough_Rider.lv2/Rough_Rider.ttl'
lv2_instantiate(0x7f83e9f861a0, 44100, /home/rocco/.lv2/Rough_Rider.lv2/, 0x25c5f70)
CarlaEngineNative::init("LV2-Export")
Using WINEPREFIX '/home/rocco/.wine', with base RT prio 15 and server RT prio 10
Starting plugin bridge, command is:
/home/rocco/.lv2/Rough_Rider.lv2//bin//carla-bridge-win64.exe "VST2" "/home/rocco/.vst/Audio Damage/Rough Rider/RoughRider_x64.dll" """" 1095004786
CarlaThread with realtime priority successful
Carla Bridge Ready!
engineCallback(7:ENGINE_CALLBACK_PARAMETER_MIDI_CC_CHANGED, 0, 0, -1, 0,000000, (null))
engineCallback(8:ENGINE_CALLBACK_PARAMETER_MIDI_CHANNEL_CHANGED, 0, 0, 0, 0,000000, (null))
engineCallback(7:ENGINE_CALLBACK_PARAMETER_MIDI_CC_CHANGED, 0, 1, -1, 0,000000, (null))
engineCallback(8:ENGINE_CALLBACK_PARAMETER_MIDI_CHANNEL_CHANGED, 0, 1, 0, 0,000000, (null))
engineCallback(7:ENGINE_CALLBACK_PARAMETER_MIDI_CC_CHANGED, 0, 2, -1, 0,000000, (null))
engineCallback(8:ENGINE_CALLBACK_PARAMETER_MIDI_CHANNEL_CHANGED, 0, 2, 0, 0,000000, (null))
engineCallback(7:ENGINE_CALLBACK_PARAMETER_MIDI_CC_CHANGED, 0, 3, -1, 0,000000, (null))
engineCallback(8:ENGINE_CALLBACK_PARAMETER_MIDI_CHANNEL_CHANGED, 0, 3, 0, 0,000000, (null))
engineCallback(7:ENGINE_CALLBACK_PARAMETER_MIDI_CC_CHANGED, 0, 4, -1, 0,000000, (null))
engineCallback(8:ENGINE_CALLBACK_PARAMETER_MIDI_CHANNEL_CHANGED, 0, 4, 0, 0,000000, (null))
engineCallback(7:ENGINE_CALLBACK_PARAMETER_MIDI_CC_CHANGED, 0, 5, -1, 0,000000, (null))
engineCallback(8:ENGINE_CALLBACK_PARAMETER_MIDI_CHANNEL_CHANGED, 0, 5, 0, 0,000000, (null))
engineCallback(9:ENGINE_CALLBACK_OPTION_CHANGED, 0, 1, 0, 0,000000, (null))
engineCallback(9:ENGINE_CALLBACK_OPTION_CHANGED, 0, 4, 1, 0,000000, (null))
engineCallback(9:ENGINE_CALLBACK_OPTION_CHANGED, 0, 16, 0, 0,000000, (null))
engineCallback(9:ENGINE_CALLBACK_OPTION_CHANGED, 0, 32, 1, 0,000000, (null))
engineCallback(9:ENGINE_CALLBACK_OPTION_CHANGED, 0, 64, 1, 0,000000, (null))
engineCallback(9:ENGINE_CALLBACK_OPTION_CHANGED, 0, 128, 1, 0,000000, (null))
engineCallback(9:ENGINE_CALLBACK_OPTION_CHANGED, 0, 256, 1, 0,000000, (null))
engineCallback(9:ENGINE_CALLBACK_OPTION_CHANGED, 0, 512, 0, 0,000000, (null))
engineCallback(1:ENGINE_CALLBACK_PLUGIN_ADDED, 0, 0, 0, 0,000000, Rough Rider)
engineCallback(35:ENGINE_CALLBACK_PROJECT_LOAD_FINISHED, 0, 0, 0, 0,000000, (null))
lv2ui_descriptor(0) has URI 'file:///home/rocco/.lv2/Rough_Rider.lv2/ext-ui'
Carla assertion failure: "index < pData->param.count" in file ../backend/plugin/CarlaPluginBridge.cpp, line 1698
`
If I try to load a second plugin in the strip Ardour returns a "fail to instantiate"
`lv2_descriptor(0) has URI 'file:///home/rocco/.lv2/Rough_Rider.lv2/Rough_Rider.ttl'
lilv_plugin_instantiate(): error: No plugin <file:///home/rocco/.lv2/BootEQmkII.lv2/BootEQmkII.ttl> in <file:///home/rocco/.lv2/BootEQmkII.lv2/BootEQmkII.so>
`
The same plugin that fails can be normally loaded in Ardour if I delete the previous plugin from the strip

I understand that the LV2 export feature is in the experimental phase: is this a known limitation of the feature?

**Comment by RockVice77** [comment] 2019-01-15 21:59
Hello,
I still have the same behavior with CARLA 2.0-RC3: no matter which is the order I use trying to  load the exported in ARDOUR, only the first plugin is actually loaded and the other plugins are failing to instantiate

**Comment by falkTX** [comment] 2019-01-16 09:38
This feature is still experimental, so not a focus for the 2.0 stable release.
I simply never tested 2 instances, error on my part, sorry.
I will try to reproduce it

**Comment by falkTX** [comment] 2019-01-16 10:00
Can't reproduce it here.
From your logs, I see that the plugin that is failing is `BootEQmkII` and not `Rough_Rider`, so actually different plugins.
Are you able to load `BootEQmkII` within ardour?

**Comment by RockVice77** [comment] 2019-01-16 20:06
Hello falkTX,
I made the attempt to load BootEQmkII first and iit works
Here follows the log from Ardour console:
`lv2_descriptor(0) has URI 'file:///home/rocco/.lv2/BootEQmkII.lv2/BootEQmkII.ttl'
lv2_instantiate(0x7f34cf7891a0, 44100, /home/rocco/.lv2/BootEQmkII.lv2/, 0x1504c380)
CarlaEngineNative::init("LV2-Export")
Using WINEPREFIX '/home/rocco/.wine', with base RT prio 15 and server RT prio 10
Starting plugin bridge, command is:
/home/rocco/.lv2/BootEQmkII.lv2//bin//carla-bridge-win32.exe "VST2" "/home/rocco/.vst/VoS_PlugIns_Complete/BootEQmkII_2.1.1/BootEQmkII.dll" """" 2032433997
CarlaThread with realtime priority successful
Carla assertion failure: "index < static_cast<int32_t>(pData->prog.count)" in file ../backend/plugin/CarlaPluginBridge.cpp, line 2080, v1 0, v2 0
Carla assertion failure: "index >= -1 && index < static_cast<int32_t>(pData->prog.count)" in file ../backend/plugin/CarlaPlugin.cpp, line 1748
Carla Bridge Ready!
engineCallback(9:ENGINE_CALLBACK_OPTION_CHANGED, 0, 4, 1, 0,000000, (null))
engineCallback(9:ENGINE_CALLBACK_OPTION_CHANGED, 0, 8, 1, 0,000000, (null))
engineCallback(9:ENGINE_CALLBACK_OPTION_CHANGED, 0, 16, 0, 0,000000, (null))
engineCallback(9:ENGINE_CALLBACK_OPTION_CHANGED, 0, 32, 1, 0,000000, (null))
engineCallback(9:ENGINE_CALLBACK_OPTION_CHANGED, 0, 64, 1, 0,000000, (null))
engineCallback(9:ENGINE_CALLBACK_OPTION_CHANGED, 0, 128, 1, 0,000000, (null))
engineCallback(9:ENGINE_CALLBACK_OPTION_CHANGED, 0, 256, 1, 0,000000, (null))
engineCallback(9:ENGINE_CALLBACK_OPTION_CHANGED, 0, 512, 0, 0,000000, (null))
engineCallback(1:ENGINE_CALLBACK_PLUGIN_ADDED, 0, 0, 0, 0,000000, BootEQmkII)
engineCallback(35:ENGINE_CALLBACK_PROJECT_LOAD_FINISHED, 0, 0, 0, 0,000000, (null))
lv2ui_descriptor(0) has URI 'file:///home/rocco/.lv2/BootEQmkII.lv2/ext-ui'
Carla assertion failure: "index < pData->param.count" in file ../backend/plugin/CarlaPluginBridge.cpp, line 1698
`
Now trying to load Rough_Rider I get again the "fail to instantiate" message and the plugin does not show up:
`lv2_descriptor(0) has URI 'file:///home/rocco/.lv2/BootEQmkII.lv2/BootEQmkII.ttl'
lilv_plugin_instantiate(): error: No plugin <file:///home/rocco/.lv2/Rough_Rider.lv2/Rough_Rider.ttl> in <file:///home/rocco/.lv2/Rough_Rider.lv2/Rough_Rider.so>
`

As an additional attempt, if at this point I try to load additional instances of BootEQmkII on some new tracks it works properly, but if I try to load any other winVST exported by Carla as LV2 the new plugin will not work. 

Addtional info:
KDE Neon 5.14.5
Ardour 5.12 64bit
Carla 2.0-RC3 from kxstudio repo
Wine Staging 4.0-rc6

**Comment by falkTX** [comment] 2019-01-16 23:44
Found the issue, I believe now fixed in latest git.
I am uploading packages to kx repos with the fix, will be there in a couple of hours.
Test when you can, version 1.9.13+git20190117, and report back.
Thanks

**Comment by RockVice77** [comment] 2019-01-17 20:58
Hello falkTX,
unfortunately after the update I still got the same behavior:

`lv2_descriptor(0) has URI 'file:///home/rocco/.lv2/BootEQmkII.lv2/BootEQmkII.ttl'
lv2_instantiate(0x7f1f9f7891a0, 44100, /home/rocco/.lv2/BootEQmkII.lv2/, 0x1424bca0)
CarlaEngineNative::init("LV2-Export")
Using WINEPREFIX '/home/rocco/.wine', with base RT prio 15 and server RT prio 10
Starting plugin bridge, command is:
/home/rocco/.lv2/BootEQmkII.lv2//bin//carla-bridge-win32.exe "VST2" "/home/rocco/.vst/VoS_PlugIns_Complete/BootEQmkII_2.1.1/BootEQmkII.dll" """" 2032433997
CarlaThread with realtime priority successful
Carla Bridge Ready!
Carla assertion failure: "index < static_cast<int32_t>(pData->prog.count)" in file ../backend/plugin/CarlaPluginBridge.cpp, line 2080, v1 0, v2 0
Carla assertion failure: "index >= -1 && index < static_cast<int32_t>(pData->prog.count)" in file ../backend/plugin/CarlaPlugin.cpp, line 1748
engineCallback(9:ENGINE_CALLBACK_OPTION_CHANGED, 0, 4, 1, 0,000000, (null))
engineCallback(9:ENGINE_CALLBACK_OPTION_CHANGED, 0, 8, 1, 0,000000, (null))
engineCallback(9:ENGINE_CALLBACK_OPTION_CHANGED, 0, 16, 0, 0,000000, (null))
engineCallback(9:ENGINE_CALLBACK_OPTION_CHANGED, 0, 32, 1, 0,000000, (null))
engineCallback(9:ENGINE_CALLBACK_OPTION_CHANGED, 0, 64, 1, 0,000000, (null))
engineCallback(9:ENGINE_CALLBACK_OPTION_CHANGED, 0, 128, 1, 0,000000, (null))
engineCallback(9:ENGINE_CALLBACK_OPTION_CHANGED, 0, 256, 1, 0,000000, (null))
engineCallback(9:ENGINE_CALLBACK_OPTION_CHANGED, 0, 512, 0, 0,000000, (null))
engineCallback(1:ENGINE_CALLBACK_PLUGIN_ADDED, 0, 0, 0, 0,000000, BootEQmkII)
engineCallback(35:ENGINE_CALLBACK_PROJECT_LOAD_FINISHED, 0, 0, 0, 0,000000, (null))
lv2ui_descriptor(0) has URI 'file:///home/rocco/.lv2/BootEQmkII.lv2/ext-ui'
Carla assertion failure: "index < pData->param.count" in file ../backend/plugin/CarlaPluginBridge.cpp, line 1698
lv2_descriptor(0) has URI 'file:///home/rocco/.lv2/BootEQmkII.lv2/BootEQmkII.ttl'
lilv_plugin_instantiate(): error: No plugin <file:///home/rocco/.lv2/Rough_Rider.lv2/Rough_Rider.ttl> in <file:///home/rocco/.lv2/Rough_Rider.lv2/Rough_Rider.so>
`

I had no success even removing all the old plugins from the .lv2 folder in my home and re-exporting the plugins with the new version of Carla 

If you have any hints for additional tests just let me know
Thanks a lot for your great effort

**Comment by falkTX** [comment] 2019-01-25 16:34
sorry for taking long on this, I have an idea of what is going on, nothing more needed.
hopefully I am able to fix this soon

**Comment by falkTX** [comment] 2019-01-26 22:01
I was able to reproduce the issue. FIxed in 570b8d5976a761073e4b579cd4c5f707019aaeb1
Bad news is that you have to reexport the plugins (or manually replace the plugin binary symlink in the lv2 plugin folder with the real file).

**Closed by falkTX** 2019-01-26 22:01 UTC
Labels: bug, needs testing

**Comment by RockVice77** [comment] 2019-01-27 09:53
Confirmed, it is fixed!
Great work
