### ISSUE TITLE
Identify plugins by a Unique ID, not only by their name

### ISSUE THREAD

**Issue by unfa** [falkTX/Carla#353] opened 2016-01-22 14:10 UTC
Problems with Carla not being able to connect my nodes together when for some reason they get "-01" appended to their names makes me wonder if using a Unique ID for plugins that Carla runs itself wouldn't be a better solution.

    <Plugin>
     <Info>
      <Type>INTERNAL</Type>
      <Name>MIDI Through</Name>
      <Label>midithrough</Label>
      <ID>4618591</ID>
     </Info>

And:

    <ExternalPatchbay>
     <Connection>
      <Source>a2j:Oxygen 49 [20] (capture): Oxygen 49 MIDI 1</Source>
      <Target>MIDI Through:events-in</Target>
      <TargetID>4618591</TargetID>
     </Connection>

If ID matches, it will connect the ports even if the names mismatch. What do you think?
Please not that in the file the MIDI Through is named like that but in reality it might be name "Midi Through-01" and I can't prevent that from happening. That'd be a nice thing to secure my patches from falling apart if something messed up with the plugin names, as it does in my case right now.

**Comment by falkTX** [comment] 2016-01-22 14:19
JACK clients are identified by their name, so there's no way around this.
Are you renaming the plugins at some point? That might be the cause here.

**Comment by unfa** [comment] 2016-01-22 22:58
I see. I'm not. But I frequently need to restart my live set. And sometimes when I do so, for example jack_mixer registers a jack client named "jack_mixer-01" and my whose setup fails there.

A script that runs my set starts by pkilling all processes that might be running to make sure the client names in jack are free. But it sometimes fails. Is there another way to make sure a client named "jack_mixer" isn't registered in jack? Can I force quit a client in jack?

**Comment by falkTX** [comment] 2016-01-22 23:16
you should wait for the clients to disappear.
the best way to achieve this is simply by stopping jack and starting it again, that way you get a 100% clean state to work with.

note that a "killall jack-mixer" will send a SIGTERM signal, which most apps intercept and start closing down (this includes carla).
the app and its client is not really closed after the killall command, but it's starting to.

**Comment by unfa** [comment] 2016-01-22 23:24
Maybe I could handle this with LADISH.

My killing procedure as follows:

     # kill all procesess to reset the studio if something is already running
     pkill -9 -f a2jmidid
     pkill -9 qsampler &
     pkill -9 -f /usr/bin/jack_mixer &
     pkill -9 -f Carla.carxp

**Comment by falkTX** [comment] 2016-01-22 23:29
don't use -9 please... I don't think jack1 likes that.
also you don't need '&' in kill commands, they only send the signal and return immediately.

and yeah, you should definitely wait for the clients to be closed first before loading the next project.
the weird client names will happen because you didn't wait.

**Comment by unfa** [comment] 2016-01-24 16:53
I updated my script. Thank you for the advice!

**Closed** 2016-01-24 16:53 UTC
