### ISSUE TITLE
Carla-rack spontaneously disables WinVSTs in Ardour

### ISSUE THREAD

**Issue by Ghaydn** [falkTX/Carla#328] opened 2015-11-30 15:28 UTC
Tested on MoonSonoSx by Elektrostudio and ComboF by Martinic. Also tried to do so with LV2 plugins (Obxd, SetBFree) - these ones work correctly. Didn't test in other apps (lmms, qtracktor).
What I did:
1. Created project in Ardour
2. Added 1-2 MIDI tracks with carla-rack as instrument
3. Added Win32 VST instrument in the rack
4. Recorded, played, saved - in different order
Spontaneously the instrument that was loaded inside Carla-rack became disabled. (red "power on" icon)
5. Turned this instrument on
6. Goto 4.
I can't catch the moment when plugins get disabled but seems that it happens when I start or stop playback.

Carla-git from kx repos
Ardour 4.4-143-g8ab69cb
Wine 1.7.52

**Comment by Ghaydn** [comment] 2015-12-04 10:30
Upd: This happens truly spontaneously. Plugins can become disabled in any moment during playback or without it.
Most often disabling plugin is ComboF.

**Comment by falkTX** [comment] 2015-12-04 10:38
This happens when the plugin takes too long to respond, sometimes wine takes a bit longer than usual.
But I guess the timer that counts the elapsed time could be wrong too.

How often does this happen to you?
Once every 30s, 1minute, 5minutes, more?

**Comment by Ghaydn** [comment] 2015-12-04 12:56
Different. From 20-30 seconds to 5-10 minutes.
I'll try to test it with wine-rt and jackd configs today or tomorrow.

**Comment by distrozapper** [comment] 2015-12-07 23:53
@Ghaydn :
Hi, reproducing your issue seems to be hard. I can see a sporadic issue with moonsonoSX (giving a sporadic crash of carla-bridge-win32.exe) though. Can you please try (and report) the use of another WinVST plugin you know "to be running" under the same (ardour4) circumstances?

**Comment by falkTX** [comment] 2015-12-26 15:45
btw, is this specific to carla as plugin?
please test it with the carla standalone.
thanks.

**Comment by SpotlightKid** [comment] 2015-12-26 16:14
I have experienced this also with the Charlatan VSTi (Win 32 or 64-bit) in Carla standalone and as plugin.

The time until the plugin is disabled varies between a few dozen seconds to several minutes.

**Comment by distrozapper** [comment] 2015-12-26 21:32
Carla-git 2:1.9.5~git20151226 standalone + Charlatan VST plugin, fed by qmidiarp 300bpm random midi sequence renders a wine crash here after about 10-16 min "continuous midi fire".
Carla terminal says this: http://kxstudio.linuxaudio.org/paste/BLisi
Note that line 30 appears about some 60s after the wine error popup is shown, which mentions carla-bridge-win32.exe having "encountered a serious problem".
Carla engine settings: JACK/Multiple Clients/Max. Param 200/"Use UI bridges instead..." unchecked/UI bridge timeout 4000/No advanced features.
JACK settings via Cadence: realtime prio 89, 44100/256/3
wine-rt: 2:1.8.0-1~trusty1

**Comment by distrozapper** [comment] 2015-12-27 18:45
With updated carla-bridge-win32/64 (2:1.9.5+git20151226), carla-git standalone behaves much more stable here, running MoonSonoSX and Charlatan VST2. No errors within 2h using the test environment above. I did not test carla as plugin in ardour though. Maybe someone else can try?

**Comment by falkTX** [comment] 2016-01-01 04:33
After some tests I found that I was missing something..
The previous build that you (distrozapper) tested proved that the new code works.
I added some debug prints and tested it myself, with and without the new 'trick'.
I can confirm that this bug is now fixed.

**Closed by falkTX** 2016-01-01 04:33 UTC
Labels: bug
