### ISSUE TITLE
Cannot enable "Send bank/program changes" for plugin

### ISSUE THREAD

**Issue by Xipazi** [falkTX/Carla#244] opened 2015-04-25 23:01 UTC
Program version: Carla-2.0beta4-win32
Engine: JACK

The option is permamently disabled.
Disabling "Map program changes" doesen't help.

**Comment by falkTX** [comment] 2015-04-25 23:04
"Send bank/program changes" is only valid for specific plugins.
(Internal Zyn, SF2/GIG giles and MIDI filters).

My bet is that you want to do something else...

**Comment by Xipazi** [comment] 2015-04-25 23:22
Hmm... maybe it is a different problem.

I have a General MIDI instrument VST synth (an old Yamaha one) that connects to a keyboard and it doesen't allow voice changes in Carla. It works without a problem in Ardour e.g.

I thought that the "Send bank/program changes" was the reason, but maybe not?

http://en.wikipedia.org/wiki/General_MIDI

According to wikipedia voice changes in general midi are achieved by program changes and it seems they are discarded by Carla?

**Comment by falkTX** [comment] 2015-04-25 23:55
carla will read the bank/program changes and map them to plugins programs/presets.
sending those midi messages directly to plugins is not supported in carla.
(with very few exceptions)

this is done by design.
we don't want the plugin changing its own presets internally.
the host is the one that should be responsible for it.

perhaps I can add vst-synths to the exception list...
what plugin are you using?

**Comment by Xipazi** [comment] 2015-04-26 01:00
OK.

In that case I don't thing it's worth adding this particular one to the exceptions, because it's old and not availble anymore.

**Comment by falkTX** [comment] 2015-04-26 20:24
hm ok then

**Comment by bencrossman** [comment] 2015-08-18 01:31
Hi

Firstly, Carla is awesome. Thank you so much for your work.
I too have a VST2 that has multiple banks. 
I am a bit puzzled though how the bank change mapping would ever work.
Say I want to change to bank 5. Most controllers will also send a MSB bank change (usually 0)
Carla picks up both MSB bank changes and LSB bank changes and treats them the same (as kEngineControlEventTypeMidiBank). So effectively we lose the information of its significance and have two bank changes of 0 and 5. Am I missing something here?

Then there's the problem of the VST2 which is using CarlaPluginJuce.cpp.
The code for bank changes is:

                    case kEngineControlEventTypeMidiBank:
                        break;

so there is currently no way to use other banks in VST2's. Shouldnt it at least be something like:

                        if ((pData->options & PLUGIN_OPTION_SEND_PROGRAM_CHANGES) != 0)
                        {
                            uint8_t midiData[3];
                            midiData[0] = uint8_t(MIDI_STATUS_CONTROL_CHANGE | (event.channel & MIDI_CHANNEL_BIT));
                            midiData[1] = MIDI_CONTROL_BANK_SELECT__LSB;
                            midiData[2] = uint8_t(ctrlEvent.value*127.0f);
                            fMidiBuffer.addEvent(midiData, 3, static_cast<int>(event.time));

                            midiData[1] = MIDI_CONTROL_BANK_SELECT; 
                            midiData[2] = 0;
                            fMidiBuffer.addEvent(midiData, 3, static_cast<int>(event.time));
                        }

And then either make the "Send bank/program changes" option not grey out or at least provide a exception list for known VST2's that have multiple banks.

The program change is currently:


                    case kEngineControlEventTypeMidiProgram:
                        if (event.channel == pData->ctrlChannel && (pData->options & PLUGIN_OPTION_MAP_PROGRAM_CHANGES) != 0)
                        {
                            if (ctrlEvent.param < pData->prog.count)
                            {
                                setProgram(ctrlEvent.param, false, false, false);
                                pData->postponeRtEvent(kPluginPostRtEventProgramChange, ctrlEvent.param, 0, 0.0f);
                                break;
                            }
                        }
                        break;

but should probably be:

                    case kEngineControlEventTypeMidiProgram:
                        if (event.channel == pData->ctrlChannel)
                        {
                            if (pData->options & PLUGIN_OPTION_MAP_PROGRAM_CHANGES) != 0)
                            {
                                if (ctrlEvent.param < pData->prog.count)
                                {
                                    setProgram(ctrlEvent.param, false, false, false);
                                    pData->postponeRtEvent(kPluginPostRtEventProgramChange, ctrlEvent.param, 0, 0.0f);
                                    break;
                                }
                            }
                            else if ((pData->options & PLUGIN_OPTION_SEND_PROGRAM_CHANGES) != 0)
                            {
                                uint8_t midiData[3];
                                midiData[0] = uint8_t(MIDI_STATUS_PROGRAM_CHANGE | (event.channel & MIDI_CHANNEL_BIT));
                                midiData[1] = uint8_t(ctrlEvent.value*127.0f);
                                fMidiBuffer.addEvent(midiData, 2, static_cast<int>(event.time));
                            }
                        }
                        break;

to match the bank stuff. This code wouldnt change how anything works at all except for the VST2's on the exception list that allowed the setting of PLUGIN_OPTION_SEND_PROGRAM_CHANGES.  Should keep everyone happy.

What do you think?
Cheers
Ben

**Comment by falkTX** [comment] 2015-08-18 09:39
I added that option recently for some LV2 MIDI filter plugins, making it available for VST is certainly doable.

I'm not sure what you mean by "VST2 that has multiple banks" though.
VST2 only provides a single list of presets to choose from, the host must load a new fxb file to change banks (not done yet in Carla).
And that has the problem of a RT operation (midi events) requiring a non-RT operation (load fxb).

The reason for ignoring MSB/LSB (0x00/0x20) is because afaik that's how the GM spec works.
XG was later introduced that joins MSB/LSB bits to form a bigger number. Please correct me if I'm wrong...
Some time later I'll implement both and make it an option in carla settings, but it's not a priority.

Anyway, implementing PLUGIN_OPTION_SEND_PROGRAM_CHANGES for VST/AU plugins is surely doable.
Not sure about the rest at the moment.

**Comment by bencrossman** [comment] 2015-08-18 10:45
Hi
Thanks for getting back to me. Sorry I probably didnt explain very well.
There are a number of old legacy VST's that work similar to the old midi hardware sound modules that use bank changes to access more than 128 sounds. The Yamaha one Xipazi mentioned above. I know of some others such as the Korg Legacy Digital Collection (M1 and Wavestation). They are wrapped in VST's but dont really work with the VST preset system. For these plugin's we really just need the program/bank messages to go straight to them rather than filtered and turned in to other event types by Carla. It really should be possible to access all these sounds without loading fxb files.

I know its a special case and probably goes against how all other plugins work but a system VST plugin option for this would be great!

Ben

**Comment by falkTX** [comment] 2015-08-18 10:51
Sure, that makes sense.
The code for this shouldn't be too complex anyway.

**Comment by SpotlightKid** [comment] 2015-08-18 10:59
Hmm, I would have expected that, if "Send Control Changes" is enabled, Carla would let any Control Change, including Bank Select, through to the plugin. If it filters it out, there should be at least an option to disable the filter (the "Send bank/Program Changes" option could be used for this).

A possible use case are MIDI filter/processing plugins.

**Comment by bencrossman** [comment] 2015-08-18 11:22
Yeah I believe even with "Send Control Changes" enabled (and therefore program mapping disabled) , Carla changes the MSB and LSB bank changes to kEngineControlEventTypeMidiBank events and therefore the VST never gets to see them since it has no code to handle these events (only kEngineEventTypeControl). I guess the proper change is probably for Carla not to filter all these events

    if (MIDI_IS_CONTROL_BANK_SELECT(midiControl)))
    {

if "Send bank/Program Changes" is enabled.

**Comment by falkTX** [comment] 2015-08-18 11:27
Bank events are special, carla will never allow those to go into the plugin unless it's very special circumstances.
Those are PLUGIN_OPTION_SEND_PROGRAM_CHANGES and midi filters.

This will be made opt-in, not opt-out.
I'll implement the option that is available for LV2 plugins for VST2 ones as well, soon.

**Comment by SpotlightKid** [comment] 2015-08-18 11:52
Opt-in is fine, IMHO, if the option exists for all plugins.

**Comment by bencrossman** [comment] 2015-08-18 12:19
Yes definitely opt-in only. It is a rare situation

**Comment by bencrossman** [comment] 2018-09-26 11:03
Hi, just wondering if the opt-in feature for vst's to receive midi bank changes is in the latest build?

Thanks
Ben

**Comment by SpotlightKid** [comment] 2018-09-26 12:44
Yes, it's in the plugin settings dialog on the first tab, the checkbox labelled "Send Bank/Program Changes". You need to uncheck "Map Program Changes" above that to be able to check it.

**Comment by bencrossman** [comment] 2018-09-26 13:46
Yeah I tried that but no bank changes making it to the VST.

In fact when I have "Send Bank/Program Changes" enabled (after disabling "Map Program Changes"), my VST2's don't receive program changes either.

At least when I had "Map Program Changes" enabled I could get some program changes if the program changes were mapped to presets (although meant bank 0 only)

**Comment by SpotlightKid** [comment] 2018-09-26 20:41
You're, it doesn't seem to be working as it should. I tested this with the following [Protoplug](http://www.osar.fr/protoplug/) script and sent Program Change and Bank Select messages via [vmpk](http://vmpk.sourceforge.net/) and neither PC nor Bank Select messages were printed, while other CC messages produced the expected output (e.g. `CC: 63 Value: 51`).

```
require "include/protoplug"

function plugin.processBlock (samples, smax, midiBuf)
    for ev in midiBuf:eachEvent() do
        if ev:isControl() then
            print('CC: ' .. ev:getControlNumber() .. " Value: " .. ev:getControlValue())
        elseif ev.data[0] >= 0xC0 and ev.data[0] < 0xD0 then
            print('PC: ' .. ev.data[1])
        else
            print("Other MIDI event, status: " .. ev.data[0])
        end
    end
end
```


I'm under the impression that this used to work, but maybe my memory is playing trick on me.

**Comment by bencrossman** [comment] 2018-09-26 20:54
Last time I looked at this stuff was a couple of years where it didn't work.

I ended up compiling from sources on Linux and doing this change to get my midi bank messages in:
`#define MIDI_IS_CONTROL_BANK_SELECT(control)           false // BC disabled bank detection so it gets passed through as normal CC

//#define MIDI_IS_CONTROL_BANK_SELECT(control)           ((control) == MIDI_CONTROL_BANK_SELECT           || (control) == MIDI_CONTROL_BANK_SELECT__LSB)`

**Comment by bencrossman** [comment] 2018-10-15 02:57
Could we get this issue reopened?

**Comment by bencrossman** [comment] 2018-10-15 03:45
From some initial digging I see two problems:

1) EngineControlEvent::convertToMidiData
turns all **MIDI_CONTROL_BANK_SELECT__LSB**'s to **MIDI_CONTROL_BANK_SELECT**'s

I know the plugins I want to do this with need both **MIDI_CONTROL_BANK_SELECT** and **MIDI_CONTROL_BANK_SELECT__LSB** Control Change MIDI messages

2) EngineEvent::fillFromMidiData
turns all **MIDI_CONTROL_BANK_SELECT__LSB**'s and **MIDI_CONTROL_BANK_SELECT**'s to **kEngineControlEventTypeMidiBank** which doesn't make it to the VST2. If I make them **kEngineControlEventTypeParameter** instead then it works.

**Comment by bencrossman** [comment] 2018-10-16 12:32
I've had another go at this:
https://github.com/falkTX/Carla/pull/782

**Comment by bencrossman** [comment] 2020-05-11 23:20
This was merged

**Comment by falkTX** [comment] 2020-05-12 07:55
right, so we can close this one

**Closed by falkTX** 2020-05-12 07:55 UTC

**Comment by farvardin** [comment] 2025-02-16 15:07
@falkTX @bencrossman I wonder if this issue should be reopened or not, I'm trying to get Roland GS instruments to work with Carla, the "send bank/program changes" is checked (btw I can't check map program changes, maybe it's normal...) but it's not the correct instrument (in this case "Brass 3" became "Brass 1"), because it looks like one bank was not taken into account (the L-bank number, which is 4, if we change it to 1 then it's Brass 1).

I'm running carla 2.6.0-alpha1 on Linux Mint 21.3

![Image](https://github.com/user-attachments/assets/ecb4644d-e1f1-46b2-a513-ada4aaf4d740)

![Image](https://github.com/user-attachments/assets/010de75d-2c08-4386-a905-3fa8bc8d5575)

This program change control works with the real hardware (sc88pro)

**Comment by gmcbretas** [comment] 2025-06-20 00:35
> [@falkTX](https://github.com/falkTX) [@bencrossman](https://github.com/bencrossman) I wonder if this issue should be reopened or not, I'm trying to get Roland GS instruments to work with Carla, the "send bank/program changes" is checked (btw I can't check map program changes, maybe it's normal...) but it's not the correct instrument (in this case "Brass 3" became "Brass 1"), because it looks like one bank was not taken into account (the L-bank number, which is 4, if we change it to 1 then it's Brass 1).
> 
> I'm running carla 2.6.0-alpha1 on Linux Mint 21.3
> 
> ![Image](https://github.com/user-attachments/assets/ecb4644d-e1f1-46b2-a513-ada4aaf4d740)
> 
> ![Image](https://github.com/user-attachments/assets/010de75d-2c08-4386-a905-3fa8bc8d5575)
> 
> This program change control works with the real hardware (sc88pro)

Same problem here with carla-bridge and Arturia Analog Lab V. lsb and msb only changes on certain conditions. I vote to open.
