### ISSUE TITLE
x42 Midi Filter not sending CC messages to plugin instrument

### ISSUE THREAD

**Issue by amsynthdotcom** [falkTX/Carla#453] opened 2017-01-10 20:29 UTC
(Debian "Jessie" 32-bit)
Regarding the x42-Midi-Filter plugin; the cc midi messages are not sent to plugin instruments except for "range include" and pitchbend.  "Range exclude", "bypass" and all other cc midi signals are lost.

brian

**Comment by aldenis** [comment] 2017-01-22 11:32
Hi,
I'm not opening a new bug report, since I believe it is the same as above.

As diagnosed in bug report https://github.com/x42/midifilter.lv2/issues/13 it looks like Carla do not deliver MIDI RT messages (clock, song position, start/stop) to LV2 MIDI plugins. It's ok with Carla internal plugins and VST plugins, but not LV2.

**Comment by falkTX** [comment] 2017-11-28 22:03
I was looking into this, but cannot reproduce.
Used the mclk plugin to generate some RT messages, then midi event filter in the middle, and a MIDI dump utility at the end.
There were some fixes regarding engine MIDI data and LV2 stuff not so long ago, so perhaps this is fixed now?
Please confirm, thank you.

**Comment by aldenis** [comment] 2017-11-28 22:22
I just tried with git master. It's fixed. Thanks!

**Comment by falkTX** [comment] 2017-11-28 22:23
Nice, thanks for confirming!

**Closed by falkTX** 2017-11-28 22:23 UTC
Labels: bug
